using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

// Dedicated settings UI for reusable Branding and Title Presets plus entry points.
public class CPHInline
{
    const string PresetsKey="rts.actionreplay.config.presets", PlayerKey="rts.actionreplay.config.player", PanelKey="rts.actionreplay.config.panel", ClapperKey="rts.actionreplay.config.clapper", Ui="rts.actionreplay.ui.presetSettings.";
    public bool Execute(){CPH.ExecuteMethod("RTS - Action Replay - Core - Presets Store","EnsureDefaults");CPH.ExecuteMethod("RTS - Action Replay - Core - Presets Store","EnsureEntryPoints");var ui=new RtsUI("RTS Action Replay Presets","1.0.0",(k,p)=>CPH.GetGlobalVar<bool?>(k,p),(k,p)=>CPH.GetGlobalVar<int?>(k,p),(k,p)=>ReadUi(k),(k,p)=>(object)CPH.GetGlobalVar<string>(k,p),(k,v,p)=>SaveUi(k,v,p),m=>CPH.LogInfo(m));Build(ui);ui.ShowUI();return true;}
    void Build(RtsUI ui){Branding(ui);TitlePresets(ui);Entries(ui,PlayerKey,"Player Entry Points",new[]{"obs","twitch","youtube","kick","recent","catalog","playlist"},new[]{"Create — OBS","Create — Twitch","Create — YouTube","Create — Kick","Play — Recent","Play — Catalog","Play — Playlist"});Entries(ui,PanelKey,"Panel Entry Points",new[]{"recent","playlist","creatorLeaderboard"},new[]{"Recent / Search","Playlist","Leaderboards"});Clapper(ui);}
    void Branding(RtsUI ui){ui.AddTitle("Reusable identity, colours and typography.","Branding Presets");foreach(var p in Presets("branding"))Brand(ui,p as JObject);}
    void Brand(RtsUI ui,JObject p){var id=(string)p["id"];if(string.IsNullOrWhiteSpace(id))return;ui.BeginSection((string)p["name"]??id,"Branding Presets");ui.BeginRow();ui.AddColorPicker("Primary Colour","Primary brand colour.","Branding Presets",K("branding",id,"primaryColor"),(string)p["primaryColor"]??"#0384CBFF");ui.AddColorPicker("Secondary Colour","Secondary brand colour.","Branding Presets",K("branding",id,"secondaryColor"),(string)p["secondaryColor"]??"#101416FF");ui.EndRow();ui.BeginRow();ui.AddColorPicker("Title Colour","Replay title colour.","Branding Presets",K("branding",id,"titleColor"),(string)p["titleColor"]??"#FFFFFFFF");ui.AddColorPicker("Title Prefix / Suffix Colour","Colour used by title prefix or suffix decoration.","Branding Presets",K("branding",id,"titlePrefixSuffixColor"),(string)p["titlePrefixSuffixColor"]??"#0384CBFF");ui.EndRow();ui.BeginRow();ui.AddColorPicker("Text Colour","General branded text colour.","Branding Presets",K("branding",id,"textColor"),(string)p["textColor"]??"#FFFFFFFF");ui.AddColorPicker("Shadow Colour","Text shadow colour.","Branding Presets",K("branding",id,"shadowColor"),(string)p["shadowColor"]??"#000000FF");ui.EndRow();ui.BeginRow();ui.AddGoogleFontSelector("Font","Google Font used by branded text.","Branding Presets",K("branding",id,"font"),(string)p["font"]??"Inter");ui.AddNumericTextbox("Font Size","Default branded font size in pixels.","Branding Presets",K("branding",id,"fontSize"),(int?)p["fontSize"]??34,12,96);ui.EndRow();ui.AddTextbox("Logo URL","HTTPS URL of the branding logo.","Branding Presets",K("branding",id,"logo"),(string)p["logo"]??"",false);ui.BeginRow();ui.AddTextbox("Fallback Text","Text used when no logo is defined.","Branding Presets",K("branding",id,"fallbackText"),(string)p["fallbackText"]??"RTS",false);ui.AddTextbox("Brand Label","Label displayed beside the logo or fallback text.","Branding Presets",K("branding",id,"brandLabel"),(string)p["brandLabel"]??"ACTION REPLAY",false);ui.EndRow();ui.EndSection();}
    void TitlePresets(RtsUI ui){ui.AddTitle("Title Presets define the configuration of each Title Design. Cinematic and Minimal are fixed designs.","Visual Presets");foreach(var p in Presets("visual")){var id=(string)p["id"];if(id=="broadcast"||id=="cut")TitlePreset(ui,p as JObject);}}
    void TitlePreset(RtsUI ui,JObject p){var id=(string)p["id"];ui.BeginSection((string)p["name"]??id,"Visual Presets");if(id=="broadcast"){Int(ui,"Chevron Height","chevronHeight",p,42,1,89);Bool(ui,"Randomize Height","randomHeight",p,false);Int(ui,"Chevron Width","chevronWidth",p,42,1,300);Bool(ui,"Randomize Width","randomWidth",p,false);Int(ui,"Chevron Spacing","chevronSpacing",p,0,0,200);Bool(ui,"Randomize Spacing","randomSpacing",p,false);Int(ui,"Chevron Speed","chevronSpeed",p,95,10,500);}else{Int(ui,"Block Width","blockWidth",p,170,1,600);Bool(ui,"Randomize Width","randomWidth",p,true);Int(ui,"Bar Height","barHeight",p,5,1,50);}ui.EndSection();}
    void Entries(RtsUI ui,string key,string cat,string[] ids,string[] labels){var c=Read(key);var a=c["entryPoints"] as JObject??new JObject();for(int i=0;i<ids.Length;i++){var e=a[ids[i]] as JObject??new JObject();ui.BeginSection(labels[i],cat);ui.AddDropdown("Animation Profile","Animation profile used by this entry point.",cat,Ui+"entry."+key+"."+ids[i]+".animation",AnimationNames(key,ids[i]),AnimationName(key,ids[i],(string)e["animationProfile"]??"default"));ui.AddDropdown("Visual Preset","Title preset used by this entry point.",cat,Ui+"entry."+key+"."+ids[i]+".visual",Names("visual"),Name("visual",(string)e["visualPreset"]??"broadcast"));ui.AddDropdown("Branding Preset","Branding preset used by this entry point.",cat,Ui+"entry."+key+"."+ids[i]+".branding",Names("branding"),Name("branding",(string)e["brandingPreset"]??"default"));ui.EndSection();}}
    void Clapper(RtsUI ui){var c=Read(ClapperKey);var e=c["entryPoint"] as JObject??new JObject();ui.AddDropdown("Animation Profile","Animation profile used by the Clapperboard.","Clapperboard",Ui+"clapper.animation",AnimationNames(ClapperKey,"entry"),AnimationName(ClapperKey,"entry",(string)e["animationProfile"]??"default"));ui.AddDropdown("Branding Preset","Branding preset used by the Clapperboard.","Clapperboard",Ui+"clapper.branding",Names("branding"),Name("branding",(string)e["brandingPreset"]??"default"));}
    string K(string t,string id,string f)=>Ui+t+"."+id+"."+f;JArray Presets(string t)=>Read(PresetsKey)[t] as JArray??new JArray();JObject Find(string t,string id){foreach(var p in Presets(t))if(string.Equals((string)p["id"],id,StringComparison.OrdinalIgnoreCase))return p as JObject;return null;}
    string[] Names(string t){var r=new List<string>();foreach(var p in Presets(t)){var n=(string)p["name"];if(!string.IsNullOrWhiteSpace(n))r.Add(n);}return r.Count>0?r.ToArray():new[]{t=="visual"?"Broadcast":"Default"};}string Name(string t,string id){var p=Find(t,id);return p==null?(t=="visual"?"Broadcast":"Default"):(string)p["name"]??id;}
    string[] AnimationNames(string key,string id){var c=Read(key);var e=key==ClapperKey?c["entryPoint"] as JObject:(c["entryPoints"] as JObject)?[id] as JObject;var a=(c["animation"] as JObject)?["profiles"] as JArray;var r=new List<string>();foreach(var p in a??new JArray()){var n=(string)p["name"];if(!string.IsNullOrWhiteSpace(n))r.Add(n);}return r.Count>0?r.ToArray():new[]{"Default"};}
    string AnimationName(string key,string id,string value){var c=Read(key);var e=key==ClapperKey?c["entryPoint"] as JObject:(c["entryPoints"] as JObject)?[id] as JObject;var a=(c["animation"] as JObject)?["profiles"] as JArray;foreach(var p in a??new JArray())if(string.Equals((string)p["id"],value,StringComparison.OrdinalIgnoreCase))return(string)p["name"]??value;return value=="default"?"Default":value;}
    string ReadUi(string key){if(!key.StartsWith(Ui,StringComparison.Ordinal))return CPH.GetGlobalVar<string>(key,true);var p=key.Substring(Ui.Length).Split('.');try{if(p[0]=="branding"||p[0]=="visual")return Find(p[0],p[1])?[p[2]]?.ToString()??"";if(p[0]=="entry")return EntryValue(p[1],p[2],p[3]);if(p[0]=="clapper")return ClapperValue(p[1]);}catch{}return"";}
    string EntryValue(string key,string id,string field){var c=Read(key);var e=(c["entryPoints"] as JObject)?[id] as JObject??new JObject();return field=="animation"?AnimationName(key,id,(string)e["animationProfile"]??"default"):Name("visual",(string)e["visualPreset"]??"broadcast");}
    string ClapperValue(string f){var c=Read(ClapperKey);var e=c["entryPoint"] as JObject??new JObject();return f=="animation"?AnimationName(ClapperKey,"entry",(string)e["animationProfile"]??"default"):Name("branding",(string)e["brandingPreset"]??"default");}
    void SaveUi(string key,object value,bool persisted){if(!key.StartsWith(Ui,StringComparison.Ordinal)){CPH.SetGlobalVar(key,value,persisted);return;}var p=key.Substring(Ui.Length).Split('.');var text=value?.ToString()??"";try{if(p[0]=="branding"||p[0]=="visual")SavePreset(p[0],p[1],p[2],text);else if(p[0]=="entry")SaveEntry(p[1],p[2],p[3],text);else if(p[0]=="clapper")SaveClapper(p[1],text);}catch(Exception ex){CPH.LogWarn("RTS Action Replay preset settings save failed: "+ex.Message);}}
    void SavePreset(string t,string id,string f,string v){var p=Find(t,id);if(p==null)return;p[f]=Parse(v);Save(PresetsKey,Read(PresetsKey));}void SaveEntry(string k,string id,string f,string v){var c=Read(k);var e=(c["entryPoints"] as JObject)?[id] as JObject??new JObject();if(f=="animation")e["animationProfile"]=ResolveAnimation(k,id,v);else e["visualPreset"]=ResolveId("visual",v);var a=c["entryPoints"] as JObject??new JObject();a[id]=e;c["entryPoints"]=a;Save(k,c);}void SaveClapper(string f,string v){var c=Read(ClapperKey);var e=c["entryPoint"] as JObject??new JObject();if(f=="animation")e["animationProfile"]=ResolveAnimation(ClapperKey,"entry",v);else e["brandingPreset"]=ResolveId("branding",v);c["entryPoint"]=e;Save(ClapperKey,c);}
    string ResolveAnimation(string key,string id,string name){var c=Read(key);var a=(c["animation"] as JObject)?["profiles"] as JArray;foreach(var p in a??new JArray())if(string.Equals((string)p["name"],name,StringComparison.OrdinalIgnoreCase))return(string)p["id"]??"default";return"default";}string ResolveId(string t,string name){var p=Find(t,name);if(p!=null)return(string)p["id"];foreach(var x in Presets(t))if(string.Equals((string)x["name"],name,StringComparison.OrdinalIgnoreCase))return(string)x["id"];return t=="visual"?"broadcast":"default";}
    void Int(RtsUI ui,string l,string f,JObject p,int d,int min,int max)=>ui.AddNumericTextbox(l,"Title preset setting.","Visual Presets",K("visual",(string)p["id"],f),(int?)p[f]??d,min,max);void Bool(RtsUI ui,string l,string f,JObject p,bool d)=>ui.AddToggleSwitch(l,"Title preset setting.","Visual Presets",K("visual",(string)p["id"],f),(bool?)p[f]??d);JObject Read(string k){var s=CPH.GetGlobalVar<string>(k,true);try{return string.IsNullOrWhiteSpace(s)?new JObject():JObject.Parse(s);}catch{return new JObject();}}void Save(string k,JObject v)=>CPH.SetGlobalVar(k,v.ToString(Newtonsoft.Json.Formatting.None),true);JToken Parse(string v){bool b;if(bool.TryParse(v,out b))return b;int i;if(int.TryParse(v,out i))return i;return v;}
}
