using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

// Settings UI for Branding Presets, Design Presets, Title Presets and entry points.
public class CPHInline
{
    const string PresetsKey="rts.actionreplay.config.presets", PlayerKey="rts.actionreplay.config.player", PanelKey="rts.actionreplay.config.panel", ClapperKey="rts.actionreplay.config.clapper", UiPrefix="rts.actionreplay.ui.presetSettings.";
    public bool Execute(){CPH.ExecuteMethod("RTS - Action Replay - Core - Presets Store","EnsureDefaults");CPH.ExecuteMethod("RTS - Action Replay - Core - Presets Store","EnsureEntryPoints");var ui=new RtsUI("RTS Action Replay Presets","1.0.0",(key,p)=>CPH.GetGlobalVar<bool?>(key,p),(key,p)=>CPH.GetGlobalVar<int?>(key,p),(key,p)=>ReadUi(key),(key,p)=>(object)CPH.GetGlobalVar<string>(key,p),(key,v,p)=>SaveUi(key,v,p),message=>CPH.LogInfo(message));Build(ui);ui.ShowUI();return true;}
    void Build(RtsUI ui){AddBranding(ui);AddDesigns(ui);AddTitles(ui);AddEntries(ui,PlayerKey,"Player Entry Points",new[]{"obs","twitch","youtube","kick","play"},new[]{"Create — OBS","Create — Twitch","Create — YouTube","Create — Kick","Play — Replay"});AddEntries(ui,PanelKey,"Panel Entry Points",new[]{"recent","playlist","creatorLeaderboard"},new[]{"Recent / Search","Playlist","Leaderboards"});AddClapper(ui);}
    void AddBranding(RtsUI ui){ui.AddTitle("Reusable identity, colours and typography.","Branding Presets");foreach(var p in Presets("branding"))AddBrandingPreset(ui,p as JObject);ui.AddClickableButton("Add Branding Preset","Create a new reusable Branding Preset.","Add Branding Preset","blue","Branding Presets",()=>{AddPreset("branding");ui.RebuildUI(Build);});}
    void AddBrandingPreset(RtsUI ui,JObject p){var id=(string)p?["id"];if(string.IsNullOrWhiteSpace(id))return;ui.BeginSection((string)p["name"]??id,"Branding Presets");ui.AddTextbox("Preset Name","Display name for this Branding Preset.","Branding Presets",K("branding",id,"name"),(string)p["name"]??"Branding",false);Dropdown(ui,"Source Platform","Optional platform this Branding Preset matches for automatic source branding.","Branding Presets",K("branding",id,"platform"),new[]{"","Twitch","Kick","YouTube"},(string)p["platform"]??"");ui.BeginRow();Colour(ui,"Primary Colour","primaryColor",p,"#0384CBFF");Colour(ui,"Secondary Colour","secondaryColor",p,"#101416FF");ui.EndRow();ui.BeginRow();Colour(ui,"Title Colour","titleColor",p,"#FFFFFFFF");Colour(ui,"Title Prefix / Suffix Colour","titlePrefixSuffixColor",p,"#0384CBFF");ui.EndRow();ui.BeginRow();Colour(ui,"Text Colour","textColor",p,"#FFFFFFFF");Colour(ui,"Shadow Colour","shadowColor",p,"#000000FF");ui.EndRow();ui.BeginRow();ui.AddGoogleFontSelector("Font","Google Font used by branded text.","Branding Presets",K("branding",id,"font"),(string)p["font"]??"Inter");ui.AddNumericTextbox("Font Size","Default branded font size in pixels.","Branding Presets",K("branding",id,"fontSize"),(int?)p["fontSize"]??34,12,96);ui.EndRow();ui.AddTextbox("Logo URL","HTTPS URL of the branding logo.","Branding Presets",K("branding",id,"logo"),(string)p["logo"]??"",false);ui.BeginRow();ui.AddTextbox("Fallback Text","Text used when no logo is defined.","Branding Presets",K("branding",id,"fallbackText"),(string)p["fallbackText"]??"RTS",false);ui.AddTextbox("Brand Label","Label displayed beside the logo or fallback text.","Branding Presets",K("branding",id,"brandLabel"),(string)p["brandLabel"]??"ACTION REPLAY",false);ui.EndRow();if(!IsBuiltInBranding(id))ui.AddClickableButton("Remove Preset","Delete this Branding Preset.","Remove Preset","red","Branding Presets",()=>{RemovePreset("branding",id);ui.RebuildUI(Build);});ui.EndSection();}
    bool IsBuiltInBranding(string id)=>id=="default"||id=="rts"||id=="twitch"||id=="youtube"||id=="kick";
    void AddDesigns(RtsUI ui){ui.AddTitle("Design Presets define the visual treatment: Broadcast, Cut, Cinematic and Minimal.","Design Presets");foreach(var id in new[]{"broadcast","cut","cinematic","minimal"}){var p=Find("visual",id);if(p!=null)AddDesign(ui,p);}}
    void AddDesign(RtsUI ui,JObject p){var id=(string)p?["id"];if(string.IsNullOrWhiteSpace(id))return;var name=(string)p["name"]??id;if(id=="broadcast"){ui.BeginSection(name,"Design Presets");Broadcast(ui,p);ui.EndSection();}else if(id=="cut"){ui.BeginSection(name,"Design Presets");Cut(ui,p);ui.EndSection();}else ui.AddTitle(name,"Design Presets");}
    void Broadcast(RtsUI ui,JObject p){ui.BeginRow();DesignInt(ui,"Chevron Height","chevronHeight",p,42,1,89);DesignBool(ui,"Randomize Height","randomHeight",p,false);DesignInt(ui,"Chevron Width","chevronWidth",p,42,1,300);DesignBool(ui,"Randomize Width","randomWidth",p,false);ui.EndRow();ui.BeginRow();DesignInt(ui,"Chevron Spacing","chevronSpacing",p,0,0,200);DesignBool(ui,"Randomize Spacing","randomSpacing",p,false);DesignInt(ui,"Chevron Speed","chevronSpeed",p,95,10,500);ui.EndRow();}
    void Cut(RtsUI ui,JObject p){ui.BeginRow();DesignInt(ui,"Block Width","blockWidth",p,170,1,600);DesignBool(ui,"Randomize Width","randomWidth",p,true);DesignInt(ui,"Bar Height","barHeight",p,5,1,50);ui.EndRow();}
    void AddTitles(RtsUI ui){ui.AddTitle("Title Presets define reusable Title Behaviour.","Title Presets");foreach(var p in Presets("title"))AddTitle(ui,p as JObject);ui.AddClickableButton("Add Title Preset","Create a new reusable Title Behaviour preset.","Add Title Preset","blue","Title Presets",()=>{AddPreset("title");ui.RebuildUI(Build);});}
    void AddTitle(RtsUI ui,JObject p){var id=(string)p?["id"];if(string.IsNullOrWhiteSpace(id))return;ui.BeginSection((string)p["name"]??id,"Title Presets");ui.AddTextbox("Preset Name","Display name for this Title Preset.","Title Presets",K("title",id,"name"),(string)p["name"]??"Title Behaviour",false);ui.BeginRow();Dropdown(ui,"Decoration Position","Position of the title prefix or suffix decoration.","Title Presets",K("title",id,"decorationPosition"),new[]{"Prefix","Suffix"},(string)p["decorationPosition"]??"Prefix");Dropdown(ui,"Title Position","Place the replay title at the top or bottom of the video.","Title Presets",K("title",id,"position"),new[]{"Top","Bottom"},(string)p["position"]??"Bottom");ui.EndRow();ui.AddTextbox("Decoration","Text added before or after the replay title.","Title Presets",K("title",id,"decoration"),(string)p["decoration"]??"Action Replay -",false);ui.BeginRow();Dropdown(ui,"Animation","Animation used when the title enters and leaves the player.","Title Presets",K("title",id,"animation"),new[]{"Left to right","Right to left","Slide up/down"},(string)p["animation"]??"Left to right");TitleInt(ui,"Show Delay","delay",p,2000,0,60000);TitleInt(ui,"Display Duration","duration",p,10000,0,120000);TitleInt(ui,"Animation Duration","animationDuration",p,1000,0,10000);ui.EndRow();if(id!="default")ui.AddClickableButton("Remove Preset","Delete this Title Preset.","Remove Preset","red","Title Presets",()=>{RemovePreset("title",id);ui.RebuildUI(Build);});ui.EndSection();}
    void AddEntries(RtsUI ui,string key,string category,string[] ids,string[] labels){var c=Read(key);var es=c["entryPoints"] as JObject??new JObject();ui.AddTitle("Each entry point selects an Animation Profile, Design Preset, Title Preset and Branding Preset.",category);if(key==PlayerKey)ui.AddToggleSwitch("Use Source Platform Branding","If enabled, use a Branding Preset assigned to the replay's source platform. If none exists, the Play — Replay Branding Preset is used.",category,EK(key,"play","useSourcePlatformBranding"),(bool?)es["play"]?["useSourcePlatformBranding"]??false);for(var i=0;i<ids.Length;i++){var id=ids[i];var e=es[id] as JObject??new JObject();ui.BeginSection(labels[i],category);ui.BeginRow();Dropdown(ui,"Branding Preset","Branding preset used by this entry point.",category,EK(key,id,"brandingPreset"),Names("branding"),Name("branding",(string)e["brandingPreset"]??"default"));Dropdown(ui,"Design Preset","Visual design used by this entry point.",category,EK(key,id,"designPreset"),Names("visual"),Name("visual",(string)e["designPreset"]??(string)e["visualPreset"]??"broadcast"));ui.EndRow();ui.BeginRow();Dropdown(ui,"Title Preset","Title Behaviour used by this entry point.",category,EK(key,id,"titlePreset"),Names("title"),Name("title",(string)e["titlePreset"]??"default"));Dropdown(ui,"Animation Profile","Animation profile used by this entry point.",category,EK(key,id,"animationProfile"),AnimationNames(key),AnimationName(key,(string)e["animationProfile"]??"default"));ui.EndRow();ui.EndSection();}}
    void AddClapper(RtsUI ui){var c=Read(ClapperKey);var e=c["entryPoint"] as JObject??new JObject();ui.AddTitle("Clapperboard uses an Animation Profile and Branding Preset.","Clapperboard");Dropdown(ui,"Animation Profile","Animation profile used by the Clapperboard.","Clapperboard",UiPrefix+"clapper.animation",AnimationNames(ClapperKey),AnimationName(ClapperKey,(string)e["animationProfile"]??"default"));Dropdown(ui,"Branding Preset","Branding preset used by the Clapperboard.","Clapperboard",UiPrefix+"clapper.branding",Names("branding"),Name("branding",(string)e["brandingPreset"]??"default"));}
    void Colour(RtsUI ui,string l,string f,JObject p,string d)=>ui.AddColorPicker(l,"Branding colour.","Branding Presets",K("branding",(string)p["id"],f),(string)p[f]??d);
    void DesignInt(RtsUI ui,string l,string f,JObject p,int d,int min,int max)=>ui.AddNumericTextbox(l,"Design preset setting.","Design Presets",K("visual",(string)p["id"],f),(int?)p[f]??d,min,max);
    void DesignBool(RtsUI ui,string l,string f,JObject p,bool d)=>ui.AddToggleSwitch(l,"Design preset setting.","Design Presets",K("visual",(string)p["id"],f),(bool?)p[f]??d);
    void TitleInt(RtsUI ui,string l,string f,JObject p,int d,int min,int max)=>ui.AddNumericTextbox(l,"Title Behaviour setting.","Title Presets",K("title",(string)p["id"],f),(int?)p[f]??d,min,max);
    void Dropdown(RtsUI ui,string l,string h,string c,string k,string[] o,string v)=>ui.AddDropdown(l,h,c,k,o,v);
    string K(string t,string id,string f)=>UiPrefix+t+"."+id+"."+f;string EK(string c,string id,string f)=>UiPrefix+"entry."+c+"."+id+"."+f;
    JArray Presets(string t)=>Read(PresetsKey)[t] as JArray??new JArray();JObject Find(string t,string id){foreach(var p in Presets(t))if(string.Equals((string)p["id"],id,StringComparison.OrdinalIgnoreCase))return p as JObject;return null;}
    string[] Names(string t){var a=new List<string>();foreach(var p in Presets(t)){var n=(string)p["name"];if(!string.IsNullOrWhiteSpace(n))a.Add(n);}return a.Count>0?a.ToArray():new[]{t=="visual"?"Broadcast":"Default"};}
    string Name(string t,string id){var p=Find(t,id);return p==null?(t=="visual"?"Broadcast":"Default"):(string)p["name"]??id;}
    JArray Animations(string k)=>Read(k)["animationProfiles"] as JArray??new JArray();string[] AnimationNames(string k){var a=new List<string>();foreach(var p in Animations(k)){var n=(string)p["name"];if(!string.IsNullOrWhiteSpace(n))a.Add(n);}return a.Count>0?a.ToArray():new[]{"Default"};}
    string AnimationName(string k,string id){foreach(var p in Animations(k))if(string.Equals((string)p["id"],id,StringComparison.OrdinalIgnoreCase))return(string)p["name"]??id;return id=="default"?"Default":id;}
    string ReadUi(string key){if(!key.StartsWith(UiPrefix,StringComparison.Ordinal))return CPH.GetGlobalVar<string>(key,true);var p=key.Substring(UiPrefix.Length).Split('.');try{if(p[0]=="branding"||p[0]=="visual"||p[0]=="title")return Find(p[0],p[1])?[p[2]]?.ToString()??"";if(p[0]=="entry")return EntryValue(p[1],p[2],p[3]);if(p[0]=="clapper")return p[1]=="animation"?AnimationName(ClapperKey,(string)Read(ClapperKey)["entryPoint"]?["animationProfile"]??"default"):Name("branding",(string)Read(ClapperKey)["entryPoint"]?["brandingPreset"]??"default");}catch{}return "";}
    string EntryValue(string c,string id,string field){var e=(Read(c)["entryPoints"] as JObject)?[id] as JObject??new JObject();if(field=="animationProfile")return AnimationName(c,(string)e[field]??"default");if(field=="useSourcePlatformBranding")return ((bool?)e[field]??false).ToString();return field=="designPreset"?Name("visual",(string)e["designPreset"]??(string)e["visualPreset"]??"broadcast"):field=="titlePreset"?Name("title",(string)e["titlePreset"]??"default"):Name("branding",(string)e["brandingPreset"]??"default");}
    void SaveUi(string key,object value,bool persisted){if(!key.StartsWith(UiPrefix,StringComparison.Ordinal)){CPH.SetGlobalVar(key,value,persisted);return;}var p=key.Substring(UiPrefix.Length).Split('.');var v=value?.ToString()??"";try{if(p[0]=="branding"||p[0]=="visual"||p[0]=="title")SavePreset(p[0],p[1],p[2],v);else if(p[0]=="entry")SaveEntry(p[1],p[2],p[3],v);else if(p[0]=="clapper")SaveClapper(p[1],v);}catch(Exception ex){CPH.LogWarn("RTS Action Replay preset settings save failed: "+ex.Message);}}
    void SavePreset(string t,string id,string f,string v){var config=Read(PresetsKey);var presets=config[t] as JArray??new JArray();JObject preset=null;foreach(var item in presets){if(string.Equals((string)item["id"],id,StringComparison.OrdinalIgnoreCase)){preset=item as JObject;break;}}if(preset==null){CPH.LogWarn("RTS Action Replay preset settings: preset not found for save: "+t+"/"+id);return;}preset[f]=Parse(v);Save(PresetsKey,config);}
    void SaveEntry(string c,string id,string f,string v){var x=Read(c);var es=x["entryPoints"] as JObject??new JObject();var e=es[id] as JObject??new JObject();if(f=="animationProfile")e[f]=ResolveAnimation(c,v);else if(f=="designPreset")e["designPreset"]=ResolveId("visual",v);else if(f=="titlePreset")e["titlePreset"]=ResolveId("title",v);else if(f=="useSourcePlatformBranding")e[f]=bool.TryParse(v,out var enabled)&&enabled;else e["brandingPreset"]=ResolveId("branding",v);es[id]=e;x["entryPoints"]=es;Save(c,x);}
    void SaveClapper(string f,string v){var x=Read(ClapperKey);var e=x["entryPoint"] as JObject??new JObject();if(f=="animation")e["animationProfile"]=ResolveAnimation(ClapperKey,v);else e["brandingPreset"]=ResolveId("branding",v);x["entryPoint"]=e;Save(ClapperKey,x);}
    string ResolveAnimation(string k,string n){foreach(var p in Animations(k))if(string.Equals((string)p["name"],n,StringComparison.OrdinalIgnoreCase))return(string)p["id"]??"default";return"default";}string ResolveId(string t,string n){foreach(var p in Presets(t))if(string.Equals((string)p["name"],n,StringComparison.OrdinalIgnoreCase))return(string)p["id"]??"default";return"default";}
    JToken Parse(string v){if(int.TryParse(v,out var i))return i;if(bool.TryParse(v,out var b))return b;return v;}JObject Read(string k,JObject f){var s=CPH.GetGlobalVar<string>(k,true);try{return string.IsNullOrWhiteSpace(s)?f:JObject.Parse(s);}catch{return f;}}void Save(string k,JObject v)=>CPH.SetGlobalVar(k,v.ToString(Newtonsoft.Json.Formatting.None),true);void AddPreset(string t){var config=Read(PresetsKey);var a=config[t] as JArray??new JArray();var source=FindInArray(a,"default");var n="New "+(t=="visual"?"Design":"Preset");var id=Guid.NewGuid().ToString("N");JObject preset;if(source!=null){preset=(JObject)source.DeepClone();preset["id"]=id;preset["name"]=n;}else{preset=new JObject{{"id",id},{"name",n}};}a.Add(preset);config[t]=a;Save(PresetsKey,config);}JObject FindInArray(JArray a,string id){foreach(var p in a??new JArray())if(string.Equals((string)p["id"],id,StringComparison.OrdinalIgnoreCase))return p as JObject;return null;}void RemovePreset(string t,string id){var config=Read(PresetsKey);var a=config[t] as JArray??new JArray();JObject p=null;foreach(var item in a){if(string.Equals((string)item["id"],id,StringComparison.OrdinalIgnoreCase)){p=item as JObject;break;}}if(p!=null)a.Remove(p);config[t]=a;Save(PresetsKey,config);}
}