using System;
using Newtonsoft.Json.Linq;

// Shared Branding, Design and Title Presets plus entry-point resolution.
public class CPHInline
{
const string PlayerKey = "rts.actionreplay.config.player";
const string PanelKey = "rts.actionreplay.config.panel";
const string ClapperKey = "rts.actionreplay.config.clapper";
const string PresetsKey = "rts.actionreplay.config.presets";
const string ResolvedPresetHandoffKey = "rts.actionreplay.handoff.resolvedPreset";
const string VisualHandoffKey = "rts.actionreplay.handoff.visualBranding";
public bool Execute() => EnsureEntryPoints();
public bool EnsureDefaults() { var p = Read(PresetsKey, Defaults()); var d = Defaults(); if (!(p["branding"] is JArray)) p["branding"] = d["branding"]; if (!(p["visual"] is JArray)) p["visual"] = d["visual"]; if (!(p["title"] is JArray)) p["title"] = TitleDefaults(); MigrateBranding(p); EnsureBranding(p); EnsureVisuals(p); EnsureTitlePresets(p); p["version"] = 4; Write(PresetsKey, p); CPH.ExecuteMethod("RTS - Action Replay - Core - Position Store", "EnsurePositions"); return true; }
public bool EnsureEntryPoints() { EnsureDefaults(); var player = Read(PlayerKey, new JObject()); var panel = Read(PanelKey, new JObject()); var clapper = Read(ClapperKey, new JObject()); MigratePlayer(player); MigratePanel(panel); MigrateClapper(clapper); Write(PlayerKey, player); Write(PanelKey, panel); Write(ClapperKey, clapper); return true; }
public bool ResolveEntryPoint() { CPH.TryGetArg("presetComponent", out string component); CPH.TryGetArg("entryPoint", out string ep); component = (component ?? "player").Trim().ToLowerInvariant(); JObject r; if (component == "panel") r = Resolve(Read(PanelKey, new JObject()), ep, new[] { "recent", "playlist", "creatorLeaderboard" }); else if (component == "clapper") r = ResolveClapper(); else if (component == "player") r = Resolve(Read(PlayerKey, new JObject()), ep, new[] { "obs", "twitch", "youtube", "kick", "play" }); else return false; CPH.SetArgument("animationProfile", (string)r["animationProfile"] ?? "default"); CPH.SetArgument("visualPreset", (string)r["designPreset"] ?? "broadcast"); CPH.SetArgument("designPreset", (string)r["designPreset"] ?? "broadcast"); CPH.SetArgument("titlePreset", (string)r["titlePreset"] ?? "default"); CPH.SetArgument("brandingPreset", (string)r["brandingPreset"] ?? "default"); CPH.SetArgument("useSourcePlatformBranding", (bool?)r["useSourcePlatformBranding"] ?? false); SaveResolvedPreset(); return true; }
public bool ResolveBrandingForSource() { if (!(CPH.TryGetArg("useSourcePlatformBranding", out bool use) && use)) return true; var source = Arg("replaySource", ""); if (string.IsNullOrWhiteSpace(source)) return true; var match = FindPlatformBranding(source); if (match != null) CPH.SetArgument("brandingPreset", (string)match["id"]); SaveResolvedPreset(); return true; }
public bool ApplyVisualAndBranding() { CPH.ExecuteMethod("RTS - Action Replay - Core - Position Store", "GetPlayerPositions"); var resolved = Read(ResolvedPresetHandoffKey, new JObject()); var did = (string)resolved["designPreset"] ?? "broadcast"; var tid = (string)resolved["titlePreset"] ?? "default"; var bid = (string)resolved["brandingPreset"] ?? "default"; var d = Find(Visuals(), did) ?? Find(Visuals(), "broadcast"); var t = Find(Titles(), tid) ?? Find(Titles(), "default"); var b = Find(Branding(), bid) ?? Find(Branding(), "default"); if (d == null || t == null || b == null) return false; var payload = BuildPayload(d, t, b); var design = (string)d["design"] ?? (string)d["id"] ?? "broadcast"; CPH.SetArgument("replayVisualPresetId", (string)d["id"]); CPH.SetArgument("replayDesignPresetId", (string)d["id"]); CPH.SetArgument("replayTitlePresetId", (string)t["id"]); CPH.SetArgument("replayBrandingPresetId", (string)b["id"]); CPH.SetArgument("replayTitleStyle", design); CPH.SetArgument("replayTitleProfileId", (string)t["id"]); CPH.SetArgument("replayTitleProfile", payload.ToString(Newtonsoft.Json.Formatting.None)); ApplyArguments(payload); var visualHandoff = payload.ToString(Newtonsoft.Json.Formatting.None); CPH.SetGlobalVar(VisualHandoffKey, visualHandoff, false); CPH.LogInfo("RTS Action Replay: panel visual handoff written to " + VisualHandoffKey); return true; }
JObject BuildPayload(JObject d, JObject t, JObject b) { return new JObject { { "profile", (string)t["id"] }, { "brandingPresetId", (string)b["id"] ?? "default" }, { "style", (string)d["design"] ?? (string)d["id"] }, { "showTitle", true }, { "decorationPosition", (string)t["decorationPosition"] ?? "Prefix" }, { "decoration", (string)t["decoration"] ?? "Action Replay -" }, { "position", (string)t["position"] ?? "Bottom" }, { "animation", (string)t["animation"] ?? "Left to right" }, { "delay", (int?)t["delay"] ?? 2000 }, { "duration", (int?)t["duration"] ?? 10000 }, { "animationDuration", (int?)t["animationDuration"] ?? 1000 }, { "font", (string)b["font"] ?? "Inter" }, { "fontSize", (int?)b["fontSize"] ?? 34 }, { "textColor", (string)b["textColor"] ?? "#FFFFFFFF" }, { "shadowColor", (string)b["shadowColor"] ?? "#000000FF" }, { "primaryColor", (string)b["primaryColor"] ?? "#0384CBFF" }, { "secondaryColor", (string)b["secondaryColor"] ?? "#101416FF" }, { "broadcast", Broadcast(d, b) }, { "cut", Cut(d, b) }, { "brandLogoUrl", (string)b["logo"] ?? "" }, { "brandFallbackText", (string)b["fallbackText"] ?? "RTS" }, { "brandLabel", (string)b["brandLabel"] ?? "ACTION REPLAY" }, { "brandFallbackTextColor", (string)b["primaryColor"] ?? "#0384CBFF" }, { "brandLabelColor", (string)b["textColor"] ?? "#FFFFFFFF" } }; }
void ApplyArguments(JObject p) { CPH.SetArgument("replayPanelPreset", (string)p["style"] ?? "broadcast"); CPH.SetArgument("replayPanelPrimaryColor", (string)p["primaryColor"] ?? "#0384CBFF"); CPH.SetArgument("replayPanelSecondaryColor", (string)p["secondaryColor"] ?? "#101416FF"); CPH.SetArgument("replayPanelTitleFont", (string)p["font"] ?? "Inter"); CPH.SetArgument("replayPanelTitleSize", (int?)p["fontSize"] ?? 34); CPH.SetArgument("replayPanelTitleColor", (string)p["textColor"] ?? "#FFFFFFFF"); CPH.SetArgument("replayPanelListColor", (string)p["textColor"] ?? "#FFFFFFFF"); CPH.SetArgument("replayShowTitle", true); CPH.SetArgument("replayTitleDecorationPosition", (string)p["decorationPosition"]); CPH.SetArgument("replayTitleDecoration", (string)p["decoration"]); CPH.SetArgument("replayTitlePosition", (string)p["position"]); CPH.SetArgument("replayTitleAnimation", (string)p["animation"]); CPH.SetArgument("replayTitleDelay", (int)p["delay"]); CPH.SetArgument("replayTitleDuration", (int)p["duration"]); CPH.SetArgument("replayTitleAnimationDuration", (int)p["animationDuration"]); CPH.SetArgument("replayTitleFont", (string)p["font"]); CPH.SetArgument("replayTitleFontSize", (int)p["fontSize"]); CPH.SetArgument("replayTitleTextColor", (string)p["textColor"]); CPH.SetArgument("replayTitleShadowColor", (string)p["shadowColor"]); CPH.SetArgument("replayTitlePrimaryColor", (string)p["primaryColor"]); CPH.SetArgument("replayTitleSecondaryColor", (string)p["secondaryColor"]); CPH.SetArgument("replayBrandLogoUrl", (string)p["brandLogoUrl"]); CPH.SetArgument("replayBrandFallbackText", (string)p["brandFallbackText"]); CPH.SetArgument("replayBrandLabel", (string)p["brandLabel"]); CPH.SetArgument("replayBrandFallbackTextColor", (string)p["brandFallbackTextColor"]); CPH.SetArgument("replayBrandLabelColor", (string)p["brandLabelColor"]); Props("replayBroadcast", p["broadcast"] as JObject); Props("replayCut", p["cut"] as JObject); }
void SaveResolvedPreset() { var data = new JObject { { "animationProfile", Arg("animationProfile", "default") }, { "designPreset", Arg("designPreset", Arg("visualPreset", "broadcast")) }, { "titlePreset", Arg("titlePreset", "default") }, { "brandingPreset", Arg("brandingPreset", "default") }, { "useSourcePlatformBranding", CPH.TryGetArg("useSourcePlatformBranding", out bool use) && use } }; CPH.SetGlobalVar(ResolvedPresetHandoffKey, data.ToString(Newtonsoft.Json.Formatting.None), false); }
JObject Broadcast(JObject d, JObject b) { return new JObject { { "primaryColor", (string)b["primaryColor"] ?? "#0384CBFF" }, { "secondaryColor", (string)b["secondaryColor"] ?? "#101416FF" }, { "chevronHeight", (int?)d["chevronHeight"] ?? 42 }, { "randomHeight", (bool?)d["randomHeight"] ?? false }, { "chevronWidth", (int?)d["chevronWidth"] ?? 42 }, { "randomWidth", (bool?)d["randomWidth"] ?? false }, { "chevronSpacing", (int?)d["chevronSpacing"] ?? 0 }, { "randomSpacing", (bool?)d["randomSpacing"] ?? false }, { "chevronSpeed", (int?)d["chevronSpeed"] ?? 95 }, { "decorationColor", (string)b["titlePrefixSuffixColor"] ?? "#0384CBFF" }, { "titleColor", (string)b["titleColor"] ?? "#FFFFFFFF" } }; }
JObject Cut(JObject d, JObject b) { return new JObject { { "primaryColor", (string)b["primaryColor"] ?? "#0384CBFF" }, { "secondaryColor", (string)b["secondaryColor"] ?? "#101416FF" }, { "blockWidth", (int?)d["blockWidth"] ?? 170 }, { "randomWidth", (bool?)d["randomWidth"] ?? true }, { "barHeight", (int?)d["barHeight"] ?? 5 }, { "decorationColor", (string)b["titlePrefixSuffixColor"] ?? "#0384CBFF" }, { "titleColor", (string)b["titleColor"] ?? "#FFFFFFFF" } }; }
void Props(string prefix, JObject o) { foreach (var x in o?.Properties() ?? new JProperty[0]) CPH.SetArgument(prefix + Cap(x.Name), Value(x.Value)); }
void MigratePlayer(JObject p) { var a = (p["animation"] as JObject)?["entryPoints"] as JObject; var old = (string)(p["title"] as JObject)?["selectedProfile"] ?? G("rts.actionreplay.titleBarStyle", "Broadcast"); var visual = Normalize(old); var entries = p["entryPoints"] as JObject ?? new JObject(); var legacyPlay = entries["catalog"] as JObject ?? entries["recent"] as JObject ?? new JObject(); foreach (var id in new[] { "obs", "twitch", "youtube", "kick", "play" }) { var source = id == "play" ? legacyPlay : entries[id] as JObject; var e = source == null ? new JObject() : (JObject)source.DeepClone(); e["animationProfile"] = (string)e["animationProfile"] ?? (string)a?[id] ?? "default"; e["visualPreset"] = (string)e["visualPreset"] ?? visual; e["titlePreset"] = (string)e["titlePreset"] ?? "default"; e["brandingPreset"] = MigrateBrandingId((string)e["brandingPreset"] ?? LegacyBranding(visual)); if (id == "play") e["useSourcePlatformBranding"] = (bool?)e["useSourcePlatformBranding"] ?? false; Put(p, id, e); } foreach (var id in new[] { "recent", "catalog", "playlist" }) entries.Remove(id); p["entryPoints"] = entries; }
void MigratePanel(JObject p) { var old = (p["preset"] as JObject) ?? new JObject(); var fallback = (string)old["fallback"] ?? "Broadcast"; var legacy = (old["entryPoints"] as JObject) ?? new JObject(); var anim = (p["animation"] as JObject)?["entryPoints"] as JObject; foreach (var id in new[] { "recent", "playlist", "creatorLeaderboard" }) { var e = p["entryPoints"]?[id] as JObject ?? new JObject(); e["animationProfile"] = (string)e["animationProfile"] ?? (string)anim?[id] ?? "default"; var visual = Normalize((string)legacy[id] ?? fallback); e["visualPreset"] = (string)e["visualPreset"] ?? visual; e["titlePreset"] = (string)e["titlePreset"] ?? "default"; e["brandingPreset"] = MigrateBrandingId((string)e["brandingPreset"] ?? LegacyBranding(visual)); Put(p, id, e); } }
void MigrateClapper(JObject c) { var e = c["entryPoint"] as JObject ?? new JObject(); e["animationProfile"] = (string)e["animationProfile"] ?? (string)(c["animation"] as JObject)?["selectedProfile"] ?? "default"; e.Remove("visualPreset"); e.Remove("titlePreset"); e["brandingPreset"] = MigrateBrandingId((string)e["brandingPreset"] ?? "default"); c["entryPoint"] = e; }
JObject Resolve(JObject c, string ep, string[] valid) { var a = c["entryPoints"] as JObject ?? new JObject(); var id = string.IsNullOrWhiteSpace(ep) ? valid[0] : ep.Trim().ToLowerInvariant(); if (Array.IndexOf(valid, id) < 0) id = valid[0]; var e = a[id] as JObject ?? new JObject(); return new JObject { { "animationProfile", (string)e["animationProfile"] ?? "default" }, { "designPreset", ResolveId(Visuals(), (string)e["designPreset"] ?? (string)e["visualPreset"] ?? "broadcast") ?? "broadcast" }, { "titlePreset", ResolveId(Titles(), (string)e["titlePreset"] ?? "default") ?? "default" }, { "brandingPreset", ResolveId(Branding(), (string)e["brandingPreset"] ?? "default") ?? "default" }, { "useSourcePlatformBranding", (bool?)e["useSourcePlatformBranding"] ?? false } }; }
JObject ResolveClapper() { var c = Read(ClapperKey, new JObject()); var e = c["entryPoint"] as JObject ?? new JObject(); return new JObject { { "animationProfile", (string)e["animationProfile"] ?? "default" }, { "brandingPreset", ResolveId(Branding(), (string)e["brandingPreset"] ?? "default") ?? "default" } }; }
public JArray Branding() => Read(PresetsKey, Defaults())["branding"] as JArray ?? new JArray();
public JArray Visuals() => Read(PresetsKey, Defaults())["visual"] as JArray ?? new JArray();
public JArray Titles() => Read(PresetsKey, Defaults())["title"] as JArray ?? new JArray();
static JObject Find(JArray a, string id) { foreach (var x in a ?? new JArray()) if (string.Equals((string)x["id"], id, StringComparison.OrdinalIgnoreCase)) return x as JObject; return null; }
static string ResolveId(JArray a, string id) { var x = Find(a, id); return x == null ? null : (string)x["id"]; }
static string Normalize(string v) { v = (v ?? "").Trim().ToLowerInvariant(); return v == "cinematic" || v == "cut" || v == "minimal" ? v : "broadcast"; }
string LegacyBranding(string v) => v == "cut" ? "twitch" : v == "broadcast" ? "rts" : "default";
string MigrateBrandingId(string id) { if (string.Equals(id, "legacy-broadcast", StringComparison.OrdinalIgnoreCase)) return "rts"; if (string.Equals(id, "legacy-cut", StringComparison.OrdinalIgnoreCase)) return "twitch"; return id; }
JObject Read(string k, JObject f) { var s = CPH.GetGlobalVar<string>(k, true); try { return string.IsNullOrWhiteSpace(s) ? f : JObject.Parse(s); } catch { return f; } }
void Write(string k, JObject v) => CPH.SetGlobalVar(k, v.ToString(Newtonsoft.Json.Formatting.None), true);
string G(string k, string d) => CPH.GetGlobalVar<string>(k, true) ?? d;
string Arg(string n, string d) => CPH.TryGetArg(n, out string v) && !string.IsNullOrWhiteSpace(v) ? v.Trim() : d;
static string Cap(string k) => char.ToUpperInvariant(k[0]) + k.Substring(1);
static object Value(JToken v) => v.Type == JTokenType.Boolean ? (object)(bool)v : v.Type == JTokenType.Integer ? (object)(int)v : v.ToString();
static void Put(JObject c, string id, JObject e) { var a = c["entryPoints"] as JObject ?? new JObject(); a[id] = e; c["entryPoints"] = a; }
JObject Defaults() { return new JObject { { "version", 4 }, { "branding", new JArray( new JObject { { "id", "default" }, { "name", "Default" }, { "platform", "" }, { "primaryColor", "#0384CBFF" }, { "secondaryColor", "#101416FF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#0384CBFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "" }, { "fallbackText", "RTS" }, { "brandLabel", "ACTION REPLAY" } }, new JObject { { "id", "rts" }, { "name", "RTS" }, { "platform", "" }, { "primaryColor", "#0384CBFF" }, { "secondaryColor", "#FFD400FF" }, { "titleColor", "#FFD400FF" }, { "titlePrefixSuffixColor", "#0384CBFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "" }, { "fallbackText", "RTS" }, { "brandLabel", "ACTION REPLAY" } }, new JObject { { "id", "twitch" }, { "name", "Twitch" }, { "platform", "Twitch" }, { "primaryColor", "#9146FFFF" }, { "secondaryColor", "#FFFFFFFF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#FFFFFFFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "https://www.freepnglogos.com/uploads/twitch-logo-vector-png-2.png" }, { "fallbackText", "Twitch" }, { "brandLabel", "" } }, new JObject { { "id", "youtube" }, { "name", "YouTube" }, { "platform", "YouTube" }, { "primaryColor", "#D4101DFF" }, { "secondaryColor", "#FFFFFFFF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#FFFFFFFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#FFFFFFFF" }, { "font", "Oswald" }, { "fontSize", 34 }, { "logo", "https://www.freepnglogos.com/uploads/youtube-logo-png/youtube-transparent-youtube-icon-29.png" }, { "fallbackText", "YouTube" }, { "brandLabel", "" } }, new JObject { { "id", "kick" }, { "name", "Kick" }, { "platform", "Kick" }, { "primaryColor", "#53FC18FF" }, { "secondaryColor", "#FFFFFFFF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#FFFFFFFF" }, { "textColor", "#000000FF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "https://static.kick.com/kick-logo.svg" }, { "fallbackText", "Kick" }, { "brandLabel", "" } } )}, { "visual", new JArray( new JObject { { "id", "broadcast" }, { "name", "Broadcast" }, { "chevronHeight", 42 }, { "randomHeight", false }, { "chevronWidth", 42 }, { "randomWidth", false }, { "chevronSpacing", 0 }, { "randomSpacing", false }, { "chevronSpeed", 95 }, { "showTitle", true }, { "design", "broadcast" }, }, new JObject { { "id", "cinematic" }, { "name", "Cinematic" }, { "fixed", true }, { "design", "cinematic" }, }, new JObject { { "id", "cut" }, { "name", "Cut" }, { "blockWidth", 170 }, { "randomWidth", true }, { "barHeight", 5 }, { "showTitle", true }, { "design", "cut" }, }, new JObject { { "id", "minimal" }, { "name", "Minimal" }, { "fixed", true }, { "design", "minimal" }, } )} }; }
JArray TitleDefaults() { var d = new JObject { { "id", "default" }, { "name", "Default" }, { "decorationPosition", G("rts.actionreplay.titleDecorationPosition", "Prefix") }, { "decoration", G("rts.actionreplay.titleDecoration", "Action Replay -") }, { "position", G("rts.actionreplay.titlePosition", "Bottom") }, { "animation", G("rts.actionreplay.titleAnimation", "Left to right") }, { "delay", CPH.GetGlobalVar<int?>("rts.actionreplay.titleDelay", true) ?? 2000 }, { "duration", CPH.GetGlobalVar<int?>("rts.actionreplay.titleDuration", true) ?? 10000 }, { "animationDuration", CPH.GetGlobalVar<int?>("rts.actionreplay.titleAnimationDuration", true) ?? 1000 } }; return new JArray(d); }
void MigrateBranding(JObject p) { var a = p["branding"] as JArray ?? new JArray(); for (var i = a.Count - 1; i >= 0; i--) { var x = a[i] as JObject; var id = (string)x?["id"]; if (string.Equals(id, "legacy-broadcast", StringComparison.OrdinalIgnoreCase) || string.Equals(id, "legacy-cut", StringComparison.OrdinalIgnoreCase)) { a.RemoveAt(i); continue; } var platform = (string)x?["platform"]; if (string.Equals(platform, "Twitch", StringComparison.OrdinalIgnoreCase)) x["id"] = "twitch"; else if (string.Equals(platform, "YouTube", StringComparison.OrdinalIgnoreCase)) x["id"] = "youtube"; else if (string.Equals(platform, "Kick", StringComparison.OrdinalIgnoreCase)) x["id"] = "kick"; } foreach (var def in Defaults()["branding"] as JArray) { var id = (string)def["id"]; if (Find(a, id) == null) a.Add(def.DeepClone()); } p["branding"] = a; }
void EnsureBranding(JObject p) { var a = p["branding"] as JArray ?? new JArray(); foreach (var x in a) if (x["platform"] == null) x["platform"] = ""; p["branding"] = a; }
JObject FindPlatformBranding(string platform) { foreach (var x in Branding()) { var p = x as JObject; if (p != null && string.Equals((string)p["platform"], platform, StringComparison.OrdinalIgnoreCase)) return p; } return null; }
void EnsureVisuals(JObject p) { var a = p["visual"] as JArray ?? new JArray(); var d = Defaults()["visual"] as JArray; foreach (var id in new[] { "broadcast", "cinematic", "cut", "minimal" }) { var x = Find(a, id); var def = Find(d, id); if (x == null) { a.Add(def.DeepClone()); continue; } if (x["design"] == null) x["design"] = (string)def["design"]; if (x["name"] == null) x["name"] = (string)def["name"]; foreach (var f in new[] { "chevronHeight", "randomHeight", "chevronWidth", "randomWidth", "chevronSpacing", "randomSpacing", "chevronSpeed", "blockWidth", "barHeight" }) if (x[f] == null && def[f] != null) x[f] = def[f]; } p["visual"] = a; }
void EnsureTitlePresets(JObject p) { var a = p["title"] as JArray ?? new JArray(); if (a.Count == 0) a = TitleDefaults(); foreach (var x in a) { if (x["name"] == null) x["name"] = (string)x["id"] ?? "Title Preset"; if (x["decorationPosition"] == null) x["decorationPosition"] = "Prefix"; if (x["position"] == null) x["position"] = "Bottom"; if (x["animation"] == null) x["animation"] = "Left to right"; if (x["delay"] == null) x["delay"] = 2000; if (x["duration"] == null) x["duration"] = 10000; if (x["animationDuration"] == null) x["animationDuration"] = 1000; } p["title"] = a; }
}