using System;
using Newtonsoft.Json.Linq;

// Shared Branding, Design and Title Presets plus entry-point resolution.
public class CPHInline
{
const string PlayerKey = "rts.actionreplay.config.player";
const string PanelKey = "rts.actionreplay.config.panel";
const string ClapperKey = "rts.actionreplay.config.clapper";
const string PresetsKey = "rts.actionreplay.config.presets";
public bool Execute() => EnsureEntryPoints();
public bool EnsureDefaults() { var p = Read(PresetsKey, Defaults()); var d = Defaults(); if (!(p["branding"] is JArray)) p["branding"] = d["branding"]; if (!(p["visual"] is JArray)) p["visual"] = d["visual"]; if (!(p["title"] is JArray)) p["title"] = TitleDefaults(); MigrateBranding(p); EnsureBranding(p); EnsureVisuals(p); EnsureTitlePresets(p); p["version"] = 4; Write(PresetsKey, p); CPH.ExecuteMethod("RTS - Action Replay - Core - Position Store", "EnsurePositions"); return true; }
public bool EnsureEntryPoints() { EnsureDefaults(); var player = Read(PlayerKey, new JObject()); var panel = Read(PanelKey, new JObject()); var clapper = Read(ClapperKey, new JObject()); MigratePlayer(player); MigratePanel(panel); MigrateClapper(clapper); Write(PlayerKey, player); Write(PanelKey, panel); Write(ClapperKey, clapper); return true; }
void MigratePlayer(JObject p) { var a = (p["animation"] as JObject)?["entryPoints"] as JObject; var old = (string)(p["title"] as JObject)?["selectedProfile"] ?? G("rts.actionreplay.titleBarStyle", "Broadcast"); var visual = Normalize(old); var entries = p["entryPoints"] as JObject ?? new JObject(); var legacyPlay = entries["catalog"] as JObject ?? entries["recent"] as JObject ?? new JObject(); foreach (var id in new[] { "obs", "twitch", "youtube", "kick", "play" }) { var source = id == "play" ? legacyPlay : entries[id] as JObject; var e = source == null ? new JObject() : (JObject)source.DeepClone(); e["animationProfile"] = (string)e["animationProfile"] ?? (string)a?[id] ?? "default"; e["visualPreset"] = (string)e["visualPreset"] ?? visual; e["titlePreset"] = (string)e["titlePreset"] ?? "default"; e["brandingPreset"] = MigrateBrandingId((string)e["brandingPreset"] ?? LegacyBranding(visual)); if (id == "play") e["useSourcePlatformBranding"] = (bool?)e["useSourcePlatformBranding"] ?? false; Put(p, id, e); } foreach (var id in new[] { "recent", "catalog", "playlist" }) entries.Remove(id); p["entryPoints"] = entries; }
void MigratePanel(JObject p) { var old = (p["preset"] as JObject) ?? new JObject(); var fallback = (string)old["fallback"] ?? "Broadcast"; var legacy = (old["entryPoints"] as JObject) ?? new JObject(); var anim = (p["animation"] as JObject)?["entryPoints"] as JObject; foreach (var id in new[] { "recent", "playlist", "creatorLeaderboard" }) { var e = p["entryPoints"]?[id] as JObject ?? new JObject(); e["animationProfile"] = (string)e["animationProfile"] ?? (string)anim?[id] ?? "default"; var visual = Normalize((string)legacy[id] ?? fallback); e["visualPreset"] = (string)e["visualPreset"] ?? visual; e["titlePreset"] = (string)e["titlePreset"] ?? "default"; e["brandingPreset"] = MigrateBrandingId((string)e["brandingPreset"] ?? LegacyBranding(visual)); Put(p, id, e); } }
void MigrateClapper(JObject c) { var e = c["entryPoint"] as JObject ?? new JObject(); e["animationProfile"] = (string)e["animationProfile"] ?? (string)(c["animation"] as JObject)?["selectedProfile"] ?? "default"; e.Remove("visualPreset"); e.Remove("titlePreset"); e["brandingPreset"] = MigrateBrandingId((string)e["brandingPreset"] ?? "default"); c["entryPoint"] = e; }
JObject Resolve(JObject c, string ep, string[] valid) { var a = c["entryPoints"] as JObject ?? new JObject(); var id = string.IsNullOrWhiteSpace(ep) ? valid[0] : ep.Trim().ToLowerInvariant(); if (Array.IndexOf(valid, id) < 0) id = valid[0]; var e = a[id] as JObject ?? new JObject(); return new JObject { { "animationProfile", (string)e["animationProfile"] ?? "default" }, { "designPreset", ResolveId(Visuals(), (string)e["designPreset"] ?? (string)e["visualPreset"] ?? "broadcast") ?? "broadcast" }, { "titlePreset", ResolveId(Titles(), (string)e["titlePreset"] ?? "default") ?? "default" }, { "brandingPreset", ResolveId(Branding(), (string)e["brandingPreset"] ?? "default") ?? "default" }, { "useSourcePlatformBranding", (bool?)e["useSourcePlatformBranding"] ?? false } }; }
JObject ResolveClapper() { var c = Read(ClapperKey, new JObject()); var e = c["entryPoint"] as JObject ?? new JObject(); return new JObject { { "animationProfile", (string)e["animationProfile"] ?? "default" }, { "brandingPreset", ResolveId(Branding(), (string)e["brandingPreset"] ?? "default") ?? "default" } }; }
public JArray Branding() => Read(PresetsKey, Defaults())["branding"] as JArray ?? new JArray();
public JArray Visuals() => Read(PresetsKey, Defaults())["visual"] as JArray ?? new JArray();
public JArray Titles() => Read(PresetsKey, Defaults())["title"] as JArray ?? new JArray();
static JObject Find(JArray a, string id) { foreach (var x in a ?? new JArray()) if (string.Equals((string)x["id"], id, StringComparison.OrdinalIgnoreCase)) return x as JObject; return null; }
static string ResolveId(JArray a, string id) { var x = Find(a, id); return x == null ? null : (string)x["id"]; }
static string Normalize(string v) { v = (v ?? "").Trim().ToLowerInvariant(); return v == "cinematic" || v == "cut" || v == "minimal" ? v : "broadcast"; }
string LegacyBranding(string v) => v == "cut" ? "twitch" : v == "broadcast" ? "rts" : "default";
string MigrateBrandingId(string id) { if (string.Equals(id, "legacy-broadcast", StringComparison.OrdinalIgnoreCase)) return "rts"; if (string.Equals(id, "legacy-cut", StringComparison.OrdinalIgnoreCase)) return "twitch"; return id; }
JObject Read(string k, JObject f) { var s = CPH.GetGlobalVar<string>(k, true); try { return string.IsNullOrWhiteSpace(s) ? f : JObject.Parse(s); } catch { return f; } }
void Write(string k, JObject v) => CPH.SetGlobalVar(k, v.ToString(Newtonsoft.Json.Formatting.None), true);
string G(string k, string d) => CPH.GetGlobalVar<string>(k, true) ?? d;
static void Put(JObject c, string id, JObject e) { var a = c["entryPoints"] as JObject ?? new JObject(); a[id] = e; c["entryPoints"] = a; }
JObject Defaults() { return new JObject { { "version", 4 }, { "branding", new JArray( new JObject { { "id", "default" }, { "name", "Default" }, { "platform", "" }, { "primaryColor", "#0384CBFF" }, { "secondaryColor", "#101416FF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#0384CBFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "" }, { "fallbackText", "RTS" }, { "brandLabel", "ACTION REPLAY" } }, new JObject { { "id", "rts" }, { "name", "RTS" }, { "platform", "" }, { "primaryColor", "#0384CBFF" }, { "secondaryColor", "#FFD400FF" }, { "titleColor", "#FFD400FF" }, { "titlePrefixSuffixColor", "#0384CBFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "" }, { "fallbackText", "RTS" }, { "brandLabel", "ACTION REPLAY" } }, new JObject { { "id", "twitch" }, { "name", "Twitch" }, { "platform", "Twitch" }, { "primaryColor", "#9146FFFF" }, { "secondaryColor", "#FFFFFFFF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#FFFFFFFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "https://www.freepnglogos.com/uploads/twitch-logo-vector-png-2.png" }, { "fallbackText", "Twitch" }, { "brandLabel", "" } }, new JObject { { "id", "youtube" }, { "name", "YouTube" }, { "platform", "YouTube" }, { "primaryColor", "#D4101DFF" }, { "secondaryColor", "#FFFFFFFF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#FFFFFFFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#FFFFFFFF" }, { "font", "Oswald" }, { "fontSize", 34 }, { "logo", "https://www.freepnglogos.com/uploads/youtube-logo-png/youtube-transparent-youtube-icon-29.png" }, { "fallbackText", "YouTube" }, { "brandLabel", "" } }, new JObject { { "id", "kick" }, { "name", "Kick" }, { "platform", "Kick" }, { "primaryColor", "#53FC18FF" }, { "secondaryColor", "#FFFFFFFF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#FFFFFFFF" }, { "textColor", "#000000FF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "https://static.kick.com/kick-logo.svg" }, { "fallbackText", "Kick" }, { "brandLabel", "" } } )}, { "visual", new JArray( new JObject { { "id", "broadcast" }, { "name", "Broadcast" }, { "chevronHeight", 42 }, { "randomHeight", false }, { "chevronWidth", 42 }, { "randomWidth", false }, { "chevronSpacing", 0 }, { "randomSpacing", false }, { "chevronSpeed", 95 }, { "showTitle", true }, { "design", "broadcast" }, }, new JObject { { "id", "cinematic" }, { "name", "Cinematic" }, { "fixed", true }, { "design", "cinematic" }, }, new JObject { { "id", "cut" }, { "name", "Cut" }, { "blockWidth", 170 }, { "randomWidth", true }, { "barHeight", 5 }, { "showTitle", true }, { "design", "cut" }, }, new JObject { { "id", "minimal" }, { "name", "Minimal" }, { "fixed", true }, { "design", "minimal" }, } )} }; }
JArray TitleDefaults() { var d = new JObject { { "id", "default" }, { "name", "Default" }, { "decorationPosition", G("rts.actionreplay.titleDecorationPosition", "Prefix") }, { "decoration", G("rts.actionreplay.titleDecoration", "Action Replay -") }, { "position", G("rts.actionreplay.titlePosition", "Bottom") }, { "animation", G("rts.actionreplay.titleAnimation", "Left to right") }, { "delay", CPH.GetGlobalVar<int?>("rts.actionreplay.titleDelay", true) ?? 2000 }, { "duration", CPH.GetGlobalVar<int?>("rts.actionreplay.titleDuration", true) ?? 10000 }, { "animationDuration", CPH.GetGlobalVar<int?>("rts.actionreplay.titleAnimationDuration", true) ?? 1000 } }; return new JArray(d); }
void MigrateBranding(JObject p) { var a = p["branding"] as JArray ?? new JArray(); for (var i = a.Count - 1; i >= 0; i--) { var x = a[i] as JObject; var id = (string)x?["id"]; if (string.Equals(id, "legacy-broadcast", StringComparison.OrdinalIgnoreCase) || string.Equals(id, "legacy-cut", StringComparison.OrdinalIgnoreCase)) { a.RemoveAt(i); continue; } var platform = (string)x?["platform"]; if (string.Equals(platform, "Twitch", StringComparison.OrdinalIgnoreCase)) x["id"] = "twitch"; else if (string.Equals(platform, "YouTube", StringComparison.OrdinalIgnoreCase)) x["id"] = "youtube"; else if (string.Equals(platform, "Kick", StringComparison.OrdinalIgnoreCase)) x["id"] = "kick"; } foreach (var def in Defaults()["branding"] as JArray) { var id = (string)def["id"]; if (Find(a, id) == null) a.Add(def.DeepClone()); } p["branding"] = a; }
void EnsureBranding(JObject p) { var a = p["branding"] as JArray ?? new JArray(); foreach (var x in a) if (x["platform"] == null) x["platform"] = ""; p["branding"] = a; }
void EnsureVisuals(JObject p) { var a = p["visual"] as JArray ?? new JArray(); var d = Defaults()["visual"] as JArray; foreach (var id in new[] { "broadcast", "cinematic", "cut", "minimal" }) { var x = Find(a, id); var def = Find(d, id); if (x == null) { a.Add(def.DeepClone()); continue; } if (x["design"] == null) x["design"] = (string)def["design"]; if (x["name"] == null) x["name"] = (string)def["name"]; foreach (var f in new[] { "chevronHeight", "randomHeight", "chevronWidth", "randomWidth", "chevronSpacing", "randomSpacing", "chevronSpeed", "blockWidth", "barHeight" }) if (x[f] == null && def[f] != null) x[f] = def[f]; } p["visual"] = a; }
void EnsureTitlePresets(JObject p) { var a = p["title"] as JArray ?? new JArray(); if (a.Count == 0) a = TitleDefaults(); foreach (var x in a) { if (x["name"] == null) x["name"] = (string)x["id"] ?? "Title Preset"; if (x["decorationPosition"] == null) x["decorationPosition"] = "Prefix"; if (x["position"] == null) x["position"] = "Bottom"; if (x["animation"] == null) x["animation"] = "Left to right"; if (x["delay"] == null) x["delay"] = 2000; if (x["duration"] == null) x["duration"] = 10000; if (x["animationDuration"] == null) x["animationDuration"] = 1000; } p["title"] = a; }
}