using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

// Settings UI for Branding Presets, Design Presets, Title Presets, Animation Profiles, Positions and entry points.
public class CPHInline
{
 const string PresetsKey="rts.actionreplay.config.presets",PlayerKey="rts.actionreplay.config.player",PanelKey="rts.actionreplay.config.panel",ClapperKey="rts.actionreplay.config.clapper",UiPrefix="rts.actionreplay.ui.presetSettings.",AnimationUiPrefix="rts.actionreplay.ui.animation.";
 public bool Execute(){CPH.ExecuteMethod("RTS - Action Replay - Core - Presets Store","EnsureDefaults");CPH.ExecuteMethod("RTS - Action Replay - Core - Presets Store","EnsureEntryPoints");CPH.ExecuteMethod("RTS - Action Replay - Core - Animation","EnsureProfiles");var ui=new RtsUI("RTS Action Replay Presets","1.0.0",ReadBool,ReadInt,(key,p)=>ReadUi(key),(key,p)=>(object)CPH.GetGlobalVar<string>(key,p),(key,v,p)=>SaveUi(key,v,p),message=>CPH.LogInfo(message));Build(ui);ui.ShowUI();return true;}
 void Build(RtsUI ui){AddBranding(ui);AddDesigns(ui);AddTitles(ui);AddAnimationProfiles(ui);AddPositions(ui);AddEntries(ui,PlayerKey,"Player Entry Points",new[]{"obs","twitch","youtube","kick","play"},new[]{"Create — OBS","Create — Twitch","Create — YouTube","Create — Kick","Play — Replay"});AddEntries(ui,PanelKey,"Panel Entry Points",new[]{"recent","playlist","creatorLeaderboard"},new[]{"Recent / Search","Playlist","Leaderboards"});AddClapper(ui);}
 void AddBranding(RtsUI ui){ui.AddTitle("Reusable identity, colours and typography.","Branding Presets");foreach(var p in Presets("branding"))AddBrandingPreset(ui,p as JObject);ui.AddClickableButton("Add Branding Preset","Create a new reusable Branding Preset.","Add Branding Preset","blue","Branding Presets",()=>{AddPreset("branding");ui.RebuildUI(Build);});}
 void AddBrandingPreset(RtsUI ui,JObject p){var id=(string)p?["id"];if(string.IsNullOrWhiteSpace(id))return;ui.BeginSection((string)p["name"]??id,"Branding Presets");ui.AddTextbox("Preset Name","Display name for this Branding Preset.","Branding Presets",K("branding",id,"name"),(string)p["name"]??"Branding",false);Dropdown(ui,"Source Platform","Optional platform this Branding Preset matches for automatic source branding.","Branding Presets",K("branding",id,"platform"),new[]{"","Twitch","Kick","YouTube"},(string)p["platform"]??"");ui.BeginRow();Colour(ui,"Primary Colour","primaryColor",p,"#0384CBFF");Colour(ui,"Secondary Colour","secondaryColor",p,"#101416FF");ui.EndRow();ui.BeginRow();Colour(ui,"Title Colour","titleColor",p,"#FFFFFFFF");Colour(ui,"Title Prefix / Suffix Colour","titlePrefixSuffixColor",p,"#0384CBFF");ui.EndRow();ui.BeginRow();Colour(ui,"Text Colour","textColor",p,"#FFFFFFFF");Colour(ui,"Shadow Colour","shadowColor",p,"#000000FF");ui.EndRow();ui.BeginRow();ui.AddGoogleFontSelector("Font","Google Font used by branded text.","Branding Presets",K("branding",id,"font"),(string)p["font"]??"Inter");ui.AddNumericTextbox("Font Size","Default branded font size in pixels.","Branding Presets",K("branding",id,"fontSize"),(int?)p["fontSize"]??34,12,96);ui.EndRow();ui.AddTextbox("Logo URL","HTTPS URL of the branding logo.","Branding Presets",K("branding",id,"logo"),(string)p["logo"]??"",false);ui.BeginRow();ui.AddTextbox("Fallback Text","Text used when no logo is defined.","Branding Presets",K("branding",id,"fallbackText"),(string)p["fallbackText"]??"RTS",false);ui.AddTextbox("Brand Label","Label displayed beside the logo or fallback text.","Branding Presets",K("branding",id,"brandLabel"),(string)p["brandLabel"]??"ACTION REPLAY",false);ui.EndRow();if(!IsBuiltInBranding(id))ui.AddClickableButton("Remove Preset","Delete this Branding Preset.","Remove Preset","red","Branding Presets",()=>{RemovePreset("branding",id);ui.RebuildUI(Build);});ui.EndSection();}
 bool IsBuiltInBranding(string id)=>id=="default"||id=="rts"||id=="twitch"||id=="youtube"||id=="kick";
 void AddDesigns(RtsUI ui){ui.AddTitle("Design Presets define the visual treatment: Broadcast, Cut, Cinematic and Minimal.","Design Presets");foreach(var id in new[]{"broadcast","cut","cinematic","minimal"}){var p=Find("visual",id);if(p!=null)AddDesign(ui,p);}}
 void AddDesign(RtsUI ui,JObject p){var id=(string)p?["id"];if(string.IsNullOrWhiteSpace(id))return;var name=(string)p["name"]??id;if(id=="broadcast"){ui.BeginSection(name,"Design Presets");Broadcast(ui,p);ui.EndSection();}else if(id=="cut"){ui.BeginSection(name,"Design Presets");Cut(ui,p);ui.EndSection();}else ui.AddTitle(name,"Design Presets");}
 void Broadcast(RtsUI ui,JObject p){ui.BeginRow();DesignInt(ui,"Chevron Height","chevronHeight",p,42,1,89);DesignBool(ui,"Randomize Height","randomHeight",p,false);DesignInt(ui,"Chevron Width","chevronWidth",p,42,1,300);DesignBool(ui,"Randomize Width","randomWidth",p,false);ui.EndRow();ui.BeginRow();DesignInt(ui,"Chevron Spacing","chevronSpacing",p,0,0,200);DesignBool(ui,"Randomize Spacing","randomSpacing",p,false);DesignInt(ui,"Chevron Speed","chevronSpeed",p,95,10,500);ui.EndRow();}
 void Cut(RtsUI ui,JObject p){ui.BeginRow();DesignInt(ui,"Block Width","blockWidth",p,170,1,600);DesignBool(ui,"Randomize Width","randomWidth",p,true);DesignInt(ui,"Bar Height","barHeight",p,5,1,50);ui.EndRow();}
 void AddTitles(RtsUI ui){ui.AddTitle("Title Presets define reusable Title Behaviour.","Title Presets");foreach(var p in Presets("title"))AddTitle(ui,p as JObject);ui.AddClickableButton("Add Title Preset","Create a new reusable Title Behaviour preset.","Add Title Preset","blue","Title Presets",()=>{AddPreset("title");ui.RebuildUI(Build);});}
 void AddTitle(RtsUI ui,JObject p){var id=(string)p?["id"];if(string.IsNullOrWhiteSpace(id))return;ui.BeginSection((string)p["name"]??id,"Title Presets");ui.AddTextbox("Preset Name","Display name for this Title Preset.","Title Presets",K("title",id,"name"),(string)p["name"]??"Title Behaviour",false);ui.BeginRow();Dropdown(ui,"Decoration Position","Position of the title prefix or suffix decoration.","Title Presets",K("title",id,"decorationPosition"),new[]{"Prefix","Suffix"},(string)p["decorationPosition"]??"Prefix");Dropdown(ui,"Title Position","Place the replay title at the top or bottom of the video.","Title Presets",K("title",id,"position"),new[]{"Top","Bottom"},(string)p["position"]??"Bottom");ui.EndRow();ui.AddTextbox("Decoration","Text added before or after the replay title.","Title Presets",K("title",id,"decoration"),(string)p["decoration"]??"Action Replay -",false);ui.BeginRow();Dropdown(ui,"Animation","Animation used when the title enters and leaves the player.","Title Presets",K("title",id,"animation"),new[]{"Left to right","Right to left","Slide up/down"},(string)p["animation"]??"Left to right");TitleInt(ui,"Show Delay","delay",p,2000,0,60000);TitleInt(ui,"Display Duration","duration",p,10000,0,120000);TitleInt(ui,"Animation Duration","animationDuration",p,1000,0,10000);ui.EndRow();if(id!="default")ui.AddClickableButton("Remove Preset","Delete this Title Preset.","Remove Preset","red","Title Presets",()=>{RemovePreset("title",id);ui.RebuildUI(Build);});ui.EndSection();}
 void AddAnimationProfiles(RtsUI ui){AddPlayerAnimationProfiles(ui);AddPanelAnimationProfiles(ui);AddClapperAnimationProfiles(ui);}
 void AddPlayerAnimationProfiles(RtsUI ui){ui.AddTitle("Reusable Player animation sequences using saved Player Positions.","Player Animation Profiles");ui.AddClickableButton("Add Profile","Create a new Player animation profile.","Add Profile","blue","Player Animation Profiles",()=>{if(CPH.ExecuteMethod("RTS - Action Replay - Core - Animation","AddProfile"))ui.RebuildUI(Build);});foreach(var p in ReadProfiles(PlayerKey)){var id=(string)p["id"];if(!string.IsNullOrWhiteSpace(id))AddAnimationProfile(ui,(string)p["name"]??"Default",id,PlayerKey,"Full Screen","Player Animation Profiles");}}
 void AddPanelAnimationProfiles(RtsUI ui){ui.AddTitle("Reusable Panel animation sequences using saved Panel Positions.","Panel Animation Profiles");ui.AddClickableButton("Add Profile","Create a new Panel animation profile.","Add Profile","blue","Panel Animation Profiles",()=>{if(CPH.ExecuteMethod("RTS - Action Replay - Core - Animation","AddPanelProfile"))ui.RebuildUI(Build);});foreach(var p in ReadProfiles(PanelKey)){var id=(string)p["id"];if(!string.IsNullOrWhiteSpace(id))AddAnimationProfile(ui,(string)p["name"]??"Default",id,PanelKey,"Centered","Panel Animation Profiles");}}
 void AddClapperAnimationProfiles(RtsUI ui){ui.AddTitle("Reusable Clapperboard animation sequences using saved Clapperboard Positions.","Clapperboard Animation Profiles");ui.AddClickableButton("Add Profile","Create a new Clapperboard animation profile.","Add Profile","blue","Clapperboard Animation Profiles",()=>{if(CPH.ExecuteMethod("RTS - Action Replay - Core - Animation","AddClapperProfile"))ui.RebuildUI(Build);});foreach(var p in ReadProfiles(ClapperKey)){var id=(string)p["id"];if(!string.IsNullOrWhiteSpace(id))AddAnimationProfile(ui,(string)p["name"]??"Default",id,ClapperKey,"Centered","Clapperboard Animation Profiles");}}
 void AddAnimationProfile(RtsUI ui,string title,string id,string key,string builtIn,string category){ui.BeginSection(title,category);if(id=="default")ui.AddTitle("Default profile is permanent. Its animation sequences can be edited.",category);else{ui.AddTextbox("Profile Name","Display name for this animation profile.",category,AnimationUiPrefix+Target(key)+".profile."+id+".name",title,false);var remove=key==PlayerKey?"RemoveProfile":key==PanelKey?"RemovePanelProfile":"RemoveClapperProfile";var arg=key==PlayerKey?"profileId":key==PanelKey?"panelProfileId":"clapperProfileId";ui.AddClickableButton("Remove Profile","Delete this animation profile.","Remove Profile","red",category,()=>{CPH.SetArgument(arg,id);if(CPH.ExecuteMethod("RTS - Action Replay - Core - Animation",remove))ui.RebuildUI(Build);});}ui.BeginRow();AddAnimationRows(ui,"Start Sequence","The positions and transitions used when this element appears.",key,id,"startSequence",builtIn,category);AddAnimationRows(ui,"End Sequence","The positions and transitions used when this element disappears.",key,id,"endSequence",builtIn,category);ui.EndRow();ui.EndSection();}
 void AddAnimationRows(RtsUI ui,string title,string description,string configKey,string profile,string sequence,string defaultPosition,string category){var target=Target(configKey);var key=AnimationUiPrefix+target+".profile."+profile+"."+sequence;var positions=AnimationPositionOptions(configKey);ui.AddDynamicRows(title,description,category,key,rows=>{rows.AddDropdown("Position","Saved position used by this animation step.",positions,defaultPosition);rows.AddNumericTextbox("Duration","Duration of the movement to this position, in milliseconds.",600,0,60000);rows.AddDropdown("Easing","Timing curve used for the movement to this position.",new[]{"linear","ease","ease-in","ease-out","ease-in-out"},"ease-in-out");rows.AddNumericTextbox("Delay","Delay before the next animation step starts, in milliseconds.",0,0,60000);},json=>SaveSequence(configKey,profile,sequence,json));}
 void AddPositions(RtsUI ui){ui.AddTitle("Reusable 3D positions shared by animation profiles and runtime playback.","Positions");AddPositionEditor(ui,"Player Positions","Saved Player positions used by Player Animation Profiles and playback.","player","Full Screen");AddPositionEditor(ui,"Panel Positions","Saved Panel positions used by Panel Animation Profiles and panel playback.","panel","Centered");AddPositionEditor(ui,"Clapperboard Positions","Saved Clapperboard positions used by Clapperboard Animation Profiles and playback.","clapperboard","Centered");}
 void AddPositionEditor(RtsUI ui,string title,string description,string target,string fallback){var key=UiPrefix+"positions."+target;var positions=PositionSet(target);var json=positions.ToString(Newtonsoft.Json.Formatting.None);CPH.SetGlobalVar(key,json,false);ui.AddPositionEditor(title,description,"Positions",key,json,edited=>SavePositions(target,key,edited),null);}
 JObject PositionSet(string target){var p=Read(PresetsKey)["positions"] as JObject;var value=p?[target] as JObject;return value??new JObject();}
 void SavePositions(string target,string uiKey,string json){try{var config=Read(PresetsKey);var positions=config["positions"] as JObject??new JObject();var value=string.IsNullOrWhiteSpace(json)?new JObject():JObject.Parse(json);positions[target]=value;config["positions"]=positions;Save(PresetsKey,config);CPH.SetGlobalVar(uiKey,value.ToString(Newtonsoft.Json.Formatting.None),false);CPH.LogInfo("RTS Action Replay: saved " + target + " positions; count="+value.Count+".");}catch(Exception ex){CPH.LogWarn("RTS Action Replay: position save failed: "+ex.Message);}}
 string Target(string key)=>key==PlayerKey?"player":key==PanelKey?"panel":"clapperboard";
 string[] AnimationPositionOptions(string key){var positions=(Read(PresetsKey)["positions"] as JObject)?[Target(key)] as JObject;var list=new List<string>{key==PlayerKey?"Full Screen":"Centered"};foreach(var item in positions??new JObject())if(!list.Contains(item.Key))list.Add(item.Key);return list.ToArray();}
 JArray ReadProfiles(string key){var profiles=Read(key)["animationProfiles"] as JArray;return profiles??new JArray(new JObject{{"id","default"},{"name","Default"},{"startSequence",new JArray()},{"endSequence",new JArray()}});}
 string ProfileName(string key,string id){foreach(var p in ReadProfiles(key))if(string.Equals((string)p["id"],id,StringComparison.Ordinal))return(string)p["name"]??"Default";return id=="default"?"Default":id;}
 void SaveAnimationName(string key,string id,string value){var c=Read(key);var p=FindProfile(c["animationProfiles"] as JArray,id);if(p==null)return;p["name"]=value;Save(key,c);}
 void SaveSequence(string key,string id,string sequence,string json){try{var c=Read(key);var p=FindProfile(c["animationProfiles"] as JArray,id);if(p==null)return;var rows=string.IsNullOrWhiteSpace(json)?new JArray():JArray.Parse(json);for(var i=0;i<rows.Count;i++){var row=rows[i] as JObject;if(row==null)continue;row["duration"]=SequenceNumber(row["duration"]);row["delay"]=SequenceNumber(row["delay"]);row["position"]=(string)row["position"]??"";row["easing"]=(string)row["easing"]??"ease-in-out";if(sequence=="startSequence"&&i==0)row["duration"]=0;}p[sequence]=rows;Save(key,c);}catch(Exception ex){CPH.LogWarn("RTS Action Replay: animation sequence save failed: "+ex.Message);}}
 int SequenceNumber(JToken v){if(v==null)return 0;int n;return int.TryParse(v.ToString(),out n)?Math.Max(0,n):0;}
 JObject FindProfile(JArray profiles,string id){foreach(var p in profiles??new JArray())if(string.Equals((string)p["id"],id,StringComparison.Ordinal))return p as JObject;return null;}
 void AddEntries(RtsUI ui,string key,string category,string[] ids,string[] labels){var c=Read(key);var es=c["entryPoints"] as JObject??new JObject();ui.AddTitle("Each entry point selects an Animation Profile, Design Preset, Title Preset and Branding Preset.",category);if(key==PlayerKey)ui.AddToggleSwitch("Use Source Platform Branding","If enabled, use a Branding Preset assigned to the replay's source platform. If none exists, the Play — Replay Branding Preset is used.",category,EK(key,"play","useSourcePlatformBranding"),ReadBool(EK(key,"play","useSourcePlatformBranding"),false)??false);for(var i=0;i<ids.Length;i++){var id=ids[i];var e=es[id] as JObject??new JObject();ui.BeginSection(labels[i],category);ui.BeginRow();Dropdown(ui,"Branding Preset","Branding preset used by this entry point.",category,EK(key,id,"brandingPreset"),Names("branding"),Name("branding",(string)e["brandingPreset"]??"default"));Dropdown(ui,"Design Preset","Visual design used by this entry point.",category,EK(key,id,"designPreset"),Names("visual"),Name("visual",(string)e["designPreset"]??(string)e["visualPreset"]??"broadcast"));ui.EndRow();ui.BeginRow();Dropdown(ui,"Title Preset","Title Behaviour used by this entry point.",category,EK(key,id,"titlePreset"),Names("title"),Name("title",(string)e["titlePreset"]??"default"));Dropdown(ui,"Animation Profile","Animation profile used by this entry point.",category,EK(key,id,"animationProfile"),AnimationNames(key),AnimationName(key,(string)e["animationProfile"]??"default"));ui.EndRow();ui.EndSection();}}
 void AddClapper(RtsUI ui){var c=Read(ClapperKey);var e=c["entryPoint"] as JObject??new JObject();ui.AddTitle("Clapperboard uses an Animation Profile and Branding Preset.","Clapperboard");Dropdown(ui,"Animation Profile","Animation profile used by the Clapperboard.","Clapperboard",UiPrefix+"clapper.animation",AnimationNames(ClapperKey),AnimationName(ClapperKey,(string)e["animationProfile"]??"default"));Dropdown(ui,"Branding Preset","Branding preset used by the Clapperboard.","Clapperboard",UiPrefix+"clapper.branding",Names("branding"),Name("branding",(string)e["brandingPreset"]??"default"));}
 void Colour(RtsUI ui,string l,string f,JObject p,string d)=>ui.AddColorPicker(l,"Branding colour.","Branding Presets",K("branding",(string)p["id"],f),(string)p[f]??d);
 void DesignInt(RtsUI ui,string l,string f,JObject p,int d,int min,int max)=>ui.AddNumericTextbox(l,"Design preset setting.","Design Presets",K("visual",(string)p["id"],f),(int?)p[f]??d,min,max);
 void DesignBool(RtsUI ui,string l,string f,JObject p,bool d)=>ui.AddToggleSwitch(l,"Design preset setting.","Design Presets",K("visual",(string)p["id"],f),(bool?)p[f]??d);
 void TitleInt(RtsUI ui,string l,string f,JObject p,int d,int min,int max)=>ui.AddNumericTextbox(l,"Title Behaviour setting.","Title Presets",K("title",(string)p["id"],f),(int?)p[f]??d,min,max);
 void Dropdown(RtsUI ui,string l,string h,string c,string k,string[] o,string v)=>ui.AddDropdown(l,h,c,k,o,v);
 string K(string t,string id,string f)=>UiPrefix+t+"."+id+"."+f;string EK(string c,string id,string f)=>UiPrefix+"entry."+EntryCode(c)+"."+id+"."+f;string EntryCode(string c)=>c==PlayerKey?"player":c==PanelKey?"panel":c;
 JArray Presets(string t)=>Read(PresetsKey)[t] as JArray??new JArray();JObject Find(string t,string id){foreach(var p in Presets(t))if(string.Equals((string)p["id"],id,StringComparison.OrdinalIgnoreCase))return p as JObject;return null;}
 string[] Names(string t){var a=new List<string>();foreach(var p in Presets(t)){var n=(string)p["name"];if(!string.IsNullOrWhiteSpace(n))a.Add(n);}return a.Count>0?a.ToArray():new[]{t=="visual"?"Broadcast":"Default"};}
 string Name(string t,string id){var p=Find(t,id);return p==null?(t=="visual"?"Broadcast":"Default"):(string)p["name"]??id;}
 JArray Animations(string k)=>Read(k)["animationProfiles"] as JArray??new JArray();string[] AnimationNames(string k){var a=new List<string>();foreach(var p in Animations(k)){var n=(string)p["name"];if(!string.IsNullOrWhiteSpace(n))a.Add(n);}return a.Count>0?a.ToArray():new[]{"Default"};}
 string AnimationName(string k,string id){foreach(var p in Animations(k))if(string.Equals((string)p["id"],id,StringComparison.OrdinalIgnoreCase))return(string)p["name"]??id;return id=="default"?"Default":id;}
 string ReadUi(string key){if(key.StartsWith(AnimationUiPrefix,StringComparison.Ordinal)){var p=key.Substring(AnimationUiPrefix.Length).Split('.');if(p.Length>=4){var config=p[0]=="player"?PlayerKey:p[0]=="panel"?PanelKey:ClapperKey;var profile=p[2];if(p[3]=="name")return ProfileName(config,profile);if(p[3]=="startSequence"||p[3]=="endSequence"){var x=FindProfile(Read(config)["animationProfiles"] as JArray,profile);return(x?[p[3]] as JArray??new JArray()).ToString(Newtonsoft.Json.Formatting.None);}}return"";}if(!key.StartsWith(UiPrefix,StringComparison.Ordinal))return CPH.GetGlobalVar<string>(key,true);var q=key.Substring(UiPrefix.Length).Split('.');try{if(q[0]=="positions")return PositionSet(q[1]).ToString(Newtonsoft.Json.Formatting.None);if(q[0]=="branding"||q[0]=="visual"||q[0]=="title")return Find(q[0],q[1])?[q[2]]?.ToString()??"";if(q[0]=="entry")return EntryValue(q[1],q[2],q[3]);if(q[0]=="clapper")return q[1]=="animation"?AnimationName(ClapperKey,(string)Read(ClapperKey)["entryPoint"]?["animationProfile"]??"default"):Name("branding",(string)Read(ClapperKey)["entryPoint"]?["brandingPreset"]??"default");}catch{}return"";}
 string EntryValue(string c,string id,string field){c=EntryKey(c);var e=(Read(c)["entryPoints"] as JObject)?[id] as JObject??new JObject();if(field=="animationProfile")return AnimationName(c,(string)e[field]??"default");if(field=="useSourcePlatformBranding")return ((bool?)e[field]??false).ToString();return field=="designPreset"?Name("visual",(string)e["designPreset"]??(string)e["visualPreset"]??"broadcast"):field=="titlePreset"?Name("title",(string)e["titlePreset"]??"default"):Name("branding",(string)e["brandingPreset"]??"default");}
 string EntryKey(string c)=>c=="player"?PlayerKey:c=="panel"?PanelKey:c;
 bool? ReadBool(string key,bool fallback){try{if(key.StartsWith(UiPrefix,StringComparison.Ordinal)){bool value;if(bool.TryParse(ReadUi(key),out value))return value;return fallback;}var raw=CPH.GetGlobalVar<string>(key,true);bool parsed;if(bool.TryParse(raw,out parsed))return parsed;return fallback;}catch{return fallback;}}
 int? ReadInt(string key,bool fallback){try{if(key.StartsWith(UiPrefix,StringComparison.Ordinal)){int value;if(int.TryParse(ReadUi(key),out value))return value;return 0;}var raw=CPH.GetGlobalVar<string>(key,true);int parsed;if(int.TryParse(raw,out parsed))return parsed;return 0;}catch{return 0;}}
 void SaveUi(string key,object value,bool persisted){if(!key.StartsWith(UiPrefix,StringComparison.Ordinal)&&!key.StartsWith(AnimationUiPrefix,StringComparison.Ordinal)){CPH.SetGlobalVar(key,value,persisted);return;}var v=value?.ToString()??"";try{if(key.StartsWith(AnimationUiPrefix,StringComparison.Ordinal)){var p=key.Substring(AnimationUiPrefix.Length).Split('.');var config=p[0]=="player"?PlayerKey:p[0]=="panel"?PanelKey:ClapperKey;if(p.Length>=4){if(p[3]=="name")SaveAnimationName(config,p[2],v);else if(p[3]=="startSequence"||p[3]=="endSequence")SaveSequence(config,p[2],p[3],v);}return;}var p2=key.Substring(UiPrefix.Length).Split('.');if(p2[0]=="positions"){SavePositions(p2[1],key,v);return;}if(p2[0]=="branding"||p2[0]=="visual"||p2[0]=="title")SavePreset(p2[0],p2[1],p2[2],v);else if(p2[0]=="entry")SaveEntry(p2[1],p2[2],p2[3],v);else if(p2[0]=="clapper")SaveClapper(p2[1],v);}catch(Exception ex){CPH.LogWarn("RTS Action Replay preset settings save failed: "+ex.Message);}}
 void SavePreset(string t,string id,string f,string v){var config=Read(PresetsKey);var presets=config[t] as JArray??new JArray();JObject preset=null;foreach(var item in presets)if(string.Equals((string)item["id"],id,StringComparison.OrdinalIgnoreCase)){preset=item as JObject;break;}if(preset==null){CPH.LogWarn("RTS Action Replay preset settings: preset not found for save: "+t+"/"+id);return;}preset[f]=Parse(v);Save(PresetsKey,config);}
 void SaveEntry(string c,string id,string f,string v){c=EntryKey(c);var x=Read(c);var es=x["entryPoints"] as JObject??new JObject();var e=es[id] as JObject??new JObject();if(f=="animationProfile")e[f]=ResolveAnimation(c,v);else if(f=="designPreset")e["designPreset"]=ResolveId("visual",v);else if(f=="titlePreset")e["titlePreset"]=ResolveId("title",v);else if(f=="useSourcePlatformBranding")e[f]=bool.TryParse(v,out var enabled)&&enabled;else e["brandingPreset"]=ResolveId("branding",v);es[id]=e;x["entryPoints"]=es;Save(c,x);}
 void SaveClapper(string f,string v){var x=Read(ClapperKey);var e=x["entryPoint"] as JObject??new JObject();if(f=="animation")e["animationProfile"]=ResolveAnimation(ClapperKey,v);else e["brandingPreset"]=ResolveId("branding",v);x["entryPoint"]=e;Save(ClapperKey,x);}
 string ResolveAnimation(string k,string n){foreach(var p in Animations(k))if(string.Equals((string)p["name"],n,StringComparison.OrdinalIgnoreCase))return(string)p["id"]??"default";return"default";}string ResolveId(string t,string n){foreach(var p in Presets(t))if(string.Equals((string)p["name"],n,StringComparison.OrdinalIgnoreCase))return(string)p["id"]??"default";return"default";}
 JToken Parse(string v){if(int.TryParse(v,out var i))return i;if(bool.TryParse(v,out var b))return b;return v;}JObject Read(string k){return Read(k,new JObject());}JObject Read(string k,JObject f){var s=CPH.GetGlobalVar<string>(k,true);try{return string.IsNullOrWhiteSpace(s)?f:JObject.Parse(s);}catch{return f;}}void Save(string k,JObject v)=>CPH.SetGlobalVar(k,v.ToString(Newtonsoft.Json.Formatting.None),true);void AddPreset(string t){var config=Read(PresetsKey);var a=config[t] as JArray??new JArray();var source=FindInArray(a,"default");var n="New "+(t=="visual"?"Design":"Preset");var id=Guid.NewGuid().ToString("N");JObject preset;if(source!=null){preset=(JObject)source.DeepClone();preset["id"]=id;preset["name"]=n;}else{preset=new JObject{{"id",id},{"name",n}};}a.Add(preset);config[t]=a;Save(PresetsKey,config);}JObject FindInArray(JArray a,string id){foreach(var p in a??new JArray())if(string.Equals((string)p["id"],id,StringComparison.OrdinalIgnoreCase))return p as JObject;return null;}void RemovePreset(string t,string id){var config=Read(PresetsKey);var a=config[t] as JArray??new JArray();JObject p=null;foreach(var item in a){if(string.Equals((string)item["id"],id,StringComparison.OrdinalIgnoreCase)){p=item as JObject;break;}}if(p!=null)a.Remove(p);config[t]=a;Save(PresetsKey,config);}
}