using System;
using System.IO;
using System.Linq;
using Microsoft.Win32;
using System.Windows;
using Newtonsoft.Json.Linq;
public class CPHInline
{
 const string D="rts.actionreplay.data",P="rts.actionreplay.config.presets",PL="rts.actionreplay.config.player",PA="rts.actionreplay.config.panel",M="rts.actionreplay.config.message",C="rts.actionreplay.config.clapper",A="rts.actionreplay.config.animation",S="rts.actionreplay.handoff.configurationSnapshot";
 public bool Execute()=>Import();
 public bool Export(){if(!CPH.ExecuteMethod("RTS - Action Replay - Core - Store","GetConfigurationSnapshot"))return false;var raw=CPH.GetGlobalVar<string>(S,false);if(string.IsNullOrWhiteSpace(raw))return false;var d=new SaveFileDialog{Title="Export RTS Action Replay Settings",Filter="RTS Action Replay Settings (*.json)|*.json|All files (*.*)|*.*",DefaultExt=".json",FileName="rts-action-replay-settings.json",OverwritePrompt=true};if(d.ShowDialog()!=true)return false;File.WriteAllText(d.FileName,raw);MessageBox.Show("Settings exported successfully.","RTS Action Replay",MessageBoxButton.OK,MessageBoxImage.Information);return true;}
 public bool Import(){var d=new OpenFileDialog{Title="Import RTS Action Replay Settings",Filter="RTS Action Replay Settings (*.json)|*.json|All files (*.*)|*.*"};if(d.ShowDialog()!=true)return false;try{var r=JObject.Parse(File.ReadAllText(d.FileName));if(r["player"]==null&&r["presets"]==null)throw new Exception("Invalid RTS Action Replay settings file.");if(MessageBox.Show("Import the selected settings from this file?","RTS Action Replay",MessageBoxButton.YesNo,MessageBoxImage.Question)!=MessageBoxResult.Yes)return false;if(B("import.player",true))Put(PL,r["player"] as JObject);if(B("import.panel",true))Put(PA,r["panel"] as JObject);if(B("import.message",true))Put(M,r["message"] as JObject);Preset("branding",r["presets"]?["branding"] as JArray,Ids("import.branding.ids"),B("import.branding",true));Preset("visual",r["presets"]?["visual"] as JArray,null,B("import.visual",true));Preset("title",r["presets"]?["title"] as JArray,null,B("import.title",true));if(B("import.animation",true))Animations(r);var n=B("import.catalog",false)?Catalog(r["data"]?["catalog"] as JArray):new int[3];Globals(r["globals"] as JObject);CPH.ExecuteMethod("RTS - Action Replay - Core - Store","EnsureDefaults");CPH.ExecuteMethod("RTS - Action Replay - Core - Store","EnsureEntryPoints");MessageBox.Show("Import completed. Catalog: "+n[0]+" added, "+n[1]+" overwritten, "+n[2]+" skipped.","RTS Action Replay",MessageBoxButton.OK,MessageBoxImage.Information);return true;}catch(Exception e){CPH.LogError("RTS Action Replay import failed: "+e.Message);MessageBox.Show("Import failed: "+e.Message,"RTS Action Replay",MessageBoxButton.OK,MessageBoxImage.Error);return false;}}
 void Preset(string t,JArray src,string[] ids,bool enabled){if(!enabled||src==null)return;bool all=Get("import."+t+".mode","All")=="All";var c=Read(P),a=c[t] as JArray??new JArray();foreach(var p in src.OfType<JObject>()){var id=(string)p["id"];if(!all&&!ids.Contains(id,StringComparer.OrdinalIgnoreCase))continue;var old=a.OfType<JObject>().FirstOrDefault(x=>string.Equals((string)x["id"],id,StringComparison.OrdinalIgnoreCase));if(old!=null){if(Get("import.duplicates","Skip")=="Skip")continue;old.Replace(p.DeepClone());}else a.Add(p.DeepClone());}c[t]=a;Save(P,c);}
 void Animations(JObject r){bool all=Get("import.animation.mode","All")=="All";var wanted=Ids("import.animation.ids");var seq=r["animation"] as JObject;foreach(var x in new[]{new[]{"player",PL},new[]{"panel",PA},new[]{"message",M},new[]{"clapperboard",C}}){var src=r[x[0]] as JObject;if(src==null)continue;var ids=all?((JArray)src["animationProfiles"]??new JArray()).OfType<JObject>().Select(p=>(string)p["id"]).ToArray():wanted.Where(i=>i.StartsWith(x[0]+":",StringComparison.OrdinalIgnoreCase)).Select(i=>i.Substring(x[0].Length+1)).ToArray();var c=Read(x[1]),a=c["animationProfiles"] as JArray??new JArray(),dest=Read(A),ds=dest[x[0]] as JObject??new JObject(),sa=src["animationProfiles"] as JArray??new JArray();foreach(var id in ids){var p=sa.OfType<JObject>().FirstOrDefault(z=>string.Equals((string)z["id"],id,StringComparison.OrdinalIgnoreCase));if(p==null)continue;var old=a.OfType<JObject>().FirstOrDefault(z=>string.Equals((string)z["id"],id,StringComparison.OrdinalIgnoreCase));if(old!=null){if(Get("import.duplicates","Skip")=="Skip")continue;old.Replace(p.DeepClone());}else a.Add(p.DeepClone());var s=seq?[x[0]]?[id];if(s!=null&&(Get("import.duplicates","Skip")=="Overwrite"||ds[id]==null))ds[id]=s.DeepClone();}c["animationProfiles"]=a;Save(x[1],c);dest[x[0]]=ds;Save(A,dest);}}
 int[] Catalog(JArray src){var n=new int[3];if(src==null)return n;var d=Read(D),a=d["catalog"] as JArray??new JArray();foreach(var p in src.OfType<JObject>()){if(!Platform((string)p["sourceType"]))continue;var old=a.OfType<JObject>().FirstOrDefault(x=>Same(x,p));if(old!=null){if(Get("import.duplicates","Skip")=="Skip"){n[2]++;continue;}old.Replace(p.DeepClone());n[1]++;}else{a.Add(p.DeepClone());n[0]++;}}d["catalog"]=a;Save(D,d);return n;}
 bool Same(JObject a,JObject b){var t=(string)b["sourceType"]??"",id=(string)b["sourceId"]??"";return id!=""&&t.Equals((string)a["sourceType"],StringComparison.OrdinalIgnoreCase)&&id.Equals((string)a["sourceId"],StringComparison.OrdinalIgnoreCase)||(t.Equals("OBS",StringComparison.OrdinalIgnoreCase)&&string.Equals((string)a["file"],(string)b["file"],StringComparison.OrdinalIgnoreCase));}
 bool Platform(string p){if(Get("import.catalog.mode","All")=="All")return true;p=(p??"").ToLowerInvariant();return B("import.catalog."+((p=="obs")?"local":p),false);}
 void Globals(JObject g){if(g==null)return;foreach(var p in g.Properties()){var k=Key(p.Name);if(k!=null&&Allowed(p.Name))CPH.SetGlobalVar(k,p.Value.Type==JTokenType.String?(object)(string)p.Value:p.Value.ToObject<object>(),true);}}
 bool Allowed(string n){if(B("import.player",true)&&"uiTheme replayFolder replayFileTypes httpMapping httpPort replayTitle newReplayTitle autoAdd autoPlay twitchPlaybackMode twitchFolder twitchHttpMapping twitchClipDuration kickPlaybackMode kickFolder kickHttpMapping youtubeClipDuration showControls showProgress playbackSpeed playbackSpeedVisibility frameColorSource frameColor controlColorSource controlColor borderGlow borderWidth cornerRadius".Split(' ').Contains(n))return true;if(B("import.panel",true)&&"panelWidth panelHeight panelCornerRadius".Split(' ').Contains(n))return true;return B("import.message",true)&&n.StartsWith("message",StringComparison.OrdinalIgnoreCase);}
 string Key(string n){var m=new System.Collections.Generic.Dictionary<string,string>{{"uiTheme","rts.actionreplay.uiTheme"},{"replayFolder","rts.actionreplay.replayFolder"},{"replayFileTypes","rts.actionreplay.replayFileTypes"},{"httpMapping","rts.actionreplay.httpMapping"},{"httpPort","rts.actionreplay.httpPort"},{"replayTitle","rts.actionreplay.replayTitle"},{"newReplayTitle","rts.actionreplay.newReplayTitle"},{"autoAdd","rts.actionreplay.autoAdd"},{"autoPlay","rts.actionreplay.autoPlay"},{"twitchPlaybackMode","rts.actionreplay.twitch.playbackMode"},{"twitchFolder","rts.actionreplay.twitch.folder"},{"twitchHttpMapping","rts.actionreplay.twitch.httpMapping"},{"twitchClipDuration","rts.actionreplay.twitch.clipDuration"},{"kickPlaybackMode","rts.actionreplay.kick.playbackMode"},{"kickFolder","rts.actionreplay.kick.folder"},{"kickHttpMapping","rts.actionreplay.kick.httpMapping"},{"youtubeClipDuration","rts.actionreplay.youtube.clipDuration"},{"showControls","rts.actionreplay.showControls"},{"showProgress","rts.actionreplay.showProgress"},{"playbackSpeed","rts.actionreplay.playbackSpeed"},{"playbackSpeedVisibility","rts.actionreplay.playbackSpeedVisibility"},{"frameColorSource","rts.actionreplay.frameColorSource"},{"frameColor","rts.actionreplay.frameColor"},{"controlColorSource","rts.actionreplay.controlColorSource"},{"controlColor","rts.actionreplay.controlColor"},{"borderGlow","rts.actionreplay.borderGlow"},{"borderWidth","rts.actionreplay.borderWidth"},{"cornerRadius","rts.actionreplay.cornerRadius"},{"panelWidth","rts.actionreplay.panel.width"},{"panelHeight","rts.actionreplay.panel.height"},{"panelCornerRadius","rts.actionreplay.panel.cornerRadius"},{"messageMinWidth","rts.actionreplay.message.minWidth"},{"messageMinHeight","rts.actionreplay.message.minHeight"},{"messageCornerRadius","rts.actionreplay.message.cornerRadius"},{"messageDuration","rts.actionreplay.message.duration"},{"messageWidth","rts.actionreplay.message.width"},{"messageHeight","rts.actionreplay.message.height"},{"messageUseSourcePlatformBranding","rts.actionreplay.message.useSourcePlatformBranding"},{"messageRecentChat","rts.actionreplay.message.recent.chat"},{"messagePlaylistChat","rts.actionreplay.message.playlist.chat"},{"messageListFormat","rts.actionreplay.message.list.format"},{"messageListMaxLength","rts.actionreplay.message.list.maxLength"}};if(m.ContainsKey(n))return m[n];foreach(var x in new[]{"Created","Queued","Renamed","Removed","Rated","Cleared","Clearedall"})if(n.StartsWith("message"+x,StringComparison.OrdinalIgnoreCase)){var rest=n.Substring(7+x.Length);return "rts.actionreplay.message."+x.ToLowerInvariant()+"."+char.ToLowerInvariant(rest[0])+rest.Substring(1);}return null;}
 string[] Ids(string k)=>Get(k,"").Split(new[]{',',';'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).ToArray();string Get(string k,string d)=>CPH.GetGlobalVar<string>(k,true)??d;bool B(string k,bool d){var v=CPH.GetGlobalVar<bool?>(k,true);return v??d;}JObject Read(string k){var s=CPH.GetGlobalVar<string>(k,true);try{return string.IsNullOrWhiteSpace(s)?new JObject():JObject.Parse(s);}catch{return new JObject();}}void Put(string k,JObject v){if(v!=null)Save(k,(JObject)v.DeepClone());}void Save(string k,JObject v)=>CPH.SetGlobalVar(k,v.ToString(Newtonsoft.Json.Formatting.None),true);
}