using System;
using System.IO;
using System.Linq;
using Newtonsoft.Json.Linq;

public class CPHInline
{
    private const string DataKey = "rts.actionreplay.data";
    private const string LegacyCatalogKey = "rts.actionreplay.catalog";
    private const string TitleKey = "rts.actionreplay.replayTitle";
    private const string PendingKey = "rts.actionreplay.pendingSaves";
    private const string FileTypesKey = "rts.actionreplay.replayFileTypes";
    private const string PlaylistAction = "RTS - Action Replay - Core - Playlist";
    private const string ReplayIdHandoffKey = "rts.actionreplay.handoff.replayId";
    private const string EntryPointHandoffKey = "rts.actionreplay.handoff.entryPoint";
    private const string ResolvedProfileHandoffKey = "rts.actionreplay.handoff.resolvedProfile";
    private const string PlayerKey = "rts.actionreplay.config.player";
    private const string PanelKey = "rts.actionreplay.config.panel";
    private const string ClapperPositionsKey = "rts.actionreplay.clapper.positions";
    private const int ClapperboardPreviewWidth = 680;
    private const int ClapperboardPreviewHeight = 372;

    public bool Execute() => Initialize();
    public bool Initialize() { Save(Load()); return true; }
    public bool Ensure() { EnsurePlayer(); EnsureObject(PanelKey, CreatePanelDefaults()); return true; }
    public bool GetPlayer() { EnsurePlayer(); CPH.SetArgument("replayPlayerConfig", Read(PlayerKey).ToString(Newtonsoft.Json.Formatting.None)); return true; }
    public bool GetPlayerPositions() { EnsurePlayer(); var player = Read(PlayerKey); CPH.SetArgument("replayPositions", ((JObject)player["positions"] ?? new JObject()).ToString(Newtonsoft.Json.Formatting.None)); return true; }
    public bool SavePlayerPositions() { EnsurePlayer(); string positionsJson; if (!CPH.TryGetArg("replayPositions", out positionsJson) || string.IsNullOrWhiteSpace(positionsJson)) return false; try { var positions = JObject.Parse(positionsJson); var player = Read(PlayerKey); player["positions"] = positions; SaveConfig(PlayerKey, player); return true; } catch (Exception ex) { CPH.LogWarn("RTS Action Replay: player position JSON save failed: " + ex.Message); return false; } }
    private void SavePlayerPositionsFromEditor(string json) { if (string.IsNullOrWhiteSpace(json)) return; try { var positions = JObject.Parse(json); var player = Read(PlayerKey); if (player.Count == 0) player = CreatePlayerDefaults(); player["positions"] = positions; SaveConfig(PlayerKey, player); } catch (Exception ex) { CPH.LogWarn("RTS Action Replay: player position editor save failed: " + ex.Message); } }
    private JObject GetPlayerPositionsObject() { EnsurePlayer(); var player = Read(PlayerKey); return (JObject)player["positions"] ?? new JObject(); }
    public bool GetPanel() { EnsureObject(PanelKey, CreatePanelDefaults()); CPH.SetArgument("replayPanelConfig", Read(PanelKey).ToString(Newtonsoft.Json.Formatting.None)); return true; }
    private void EnsurePlayer() { var current = Read(PlayerKey); if (current.Count > 0) return; SaveConfig(PlayerKey, CreatePlayerDefaults()); }
    private JObject CreatePlayerDefaults() => new JObject { ["version"] = 1, ["positions"] = new JObject { ["Full Screen"] = new JObject { ["name"] = "Full Screen", ["tag"] = "full-screen", ["scale"] = 100, ["scaleX"] = 100, ["scaleY"] = 100, ["x"] = 0, ["y"] = 0, ["z"] = 0, ["rotateX"] = 0, ["rotateY"] = 0, ["rotateZ"] = 0, ["fov"] = 90 } }, ["animationProfiles"] = new JArray { new JObject { ["id"] = "default", ["name"] = "Default", ["startSequence"] = new JArray(), ["endSequence"] = new JArray() } }, ["animation"] = new JObject { ["selectedProfile"] = "default", ["entryPoints"] = new JObject { ["obs"] = "default", ["twitch"] = "default", ["recent"] = "default", ["catalog"] = "default", ["playlist"] = "default" } } };
    private JObject CreatePanelDefaults() => new JObject { ["version"] = 1, ["width"] = 500, ["height"] = 700, ["positions"] = new JObject { ["Centered"] = new JObject { ["name"] = "Centered", ["tag"] = "centered", ["scale"] = 100, ["scaleX"] = 100, ["scaleY"] = 100, ["x"] = 0, ["y"] = 0, ["z"] = 0, ["rotateX"] = 0, ["rotateY"] = 0, ["rotateZ"] = 0, ["fov"] = 90 } }, ["animationProfiles"] = new JArray { new JObject { ["id"] = "default", ["name"] = "Default", ["startSequence"] = new JArray(), ["endSequence"] = new JArray() } }, ["animation"] = new JObject { ["entryPoints"] = new JObject { ["recent"] = "default", ["playlist"] = "default", ["creatorLeaderboard"] = "default" } } };
    private JObject Read(string key) { var raw = CPH.GetGlobalVar<string>(key, true); if (string.IsNullOrWhiteSpace(raw)) return new JObject(); try { return JObject.Parse(raw); } catch { return new JObject(); } }
    private void EnsureObject(string key, JObject defaults) { var current = Read(key); if (current.Count == 0) SaveConfig(key, defaults); }
    private void SaveConfig(string key, JObject value) => CPH.SetGlobalVar(key, value.ToString(Newtonsoft.Json.Formatting.None), true);

    public bool AddReplay()
    {
        if (!(CPH.GetGlobalVar<bool?>("rts.actionreplay.autoAdd", true) ?? true)) return true; string path; if (!CPH.TryGetArg("fullPath", out path) || string.IsNullOrWhiteSpace(path) || !File.Exists(path) || !IsReplayFile(path)) return false; var folder = CPH.GetGlobalVar<string>("rts.actionreplay.replayFolder", true); if (!string.IsNullOrWhiteSpace(folder) && !Path.GetFullPath(path).StartsWith(Path.GetFullPath(folder).TrimEnd('\\') + "\\", StringComparison.OrdinalIgnoreCase)) return false; if (Path.GetExtension(path).Equals(".tmp", StringComparison.OrdinalIgnoreCase) || !Stable(path)) return false; var data = Load(); var catalog = GetCatalog(data); var file = Path.GetFileName(path); if (catalog.OfType<JObject>().Any(x => string.Equals((string)x["file"], file, StringComparison.OrdinalIgnoreCase) && string.Equals((string)x["sourceType"] ?? "OBS", "OBS", StringComparison.OrdinalIgnoreCase))) return true; var now = DateTime.Now; var id = now.ToString("yyyyMMdd-HHmmssfff") + "-" + Guid.NewGuid().ToString("N").Substring(0, 6); var creatorId = Get("userId"); var creatorName = Get("userName"); var creatorPlatform = NormalizePlatform(Get("userType")); ApplyPendingCreator(ref creatorPlatform, ref creatorId, ref creatorName); CPH.SetArgument("replayId", id); CPH.SetArgument("replayFile", file); CPH.SetArgument("replayPath", path); CPH.SetArgument("replayName", Path.GetFileNameWithoutExtension(path)); CPH.SetArgument("replayNumber", 1); CPH.SetArgument("replayDate", now.ToString("yyyy-MM-dd")); CPH.SetArgument("replayTime", now.ToString("HH:mm:ss")); CPH.SetArgument("replayPlays", 0); CPH.SetArgument("replayUser", creatorName); CPH.SetArgument("replayUserId", creatorId); CPH.SetArgument("replayPlatform", creatorPlatform); CPH.SetArgument("replayUserPlays", 0); CPH.SetArgument("replayTitle", ""); var title = CPH.Parse(CPH.GetGlobalVar<string>(TitleKey, true) ?? "%replayName%"); if (string.IsNullOrWhiteSpace(title)) title = Path.GetFileNameWithoutExtension(path); var replay = new JObject { ["id"] = id, ["sourceType"] = "OBS", ["sourceId"] = id, ["file"] = file, ["filePath"] = path, ["title"] = title, ["customTitle"] = false, ["added"] = now.ToString("o"), ["captured"] = now.ToString("o"), ["acquisitionMethod"] = "OBSReplayBuffer", ["creator"] = new JObject { ["platform"] = creatorPlatform, ["id"] = creatorId, ["name"] = creatorName }, ["plays"] = 0, ["users"] = new JObject() }; catalog.Insert(0, replay); Save(data); CPH.LogInfo($"RTS Action Replay: added {title} ({id})"); CPH.SetArgument("replayTitle", title); CPH.SetArgument("animationEntryPoint", "obs"); CPH.SetArgument("replayAutoPlay", CPH.GetGlobalVar<bool?>("rts.actionreplay.autoPlay", true) ?? false); SendStoreMessage("save"); return true;
    }
    public bool NameReplay() { string indexInput; string rawInput; if (!CPH.TryGetArg("input0", out indexInput) || !CPH.TryGetArg("rawInput", out rawInput)) return false; if (!int.TryParse(indexInput, out var index)) { CPH.SendMessage("Please provide a valid replay number."); return false; } var title = (rawInput ?? "").Trim(); if (title.StartsWith(indexInput + " ", StringComparison.OrdinalIgnoreCase)) title = title.Substring(indexInput.Length).Trim(); if (title.Length == 0) { CPH.SendMessage("Please provide a replay title."); return false; } var data = Load(); var list = GetCatalog(data); if (index < 1 || index > list.Count) { CPH.SendMessage($"Replay #{index} does not exist."); return false; } var target = (JObject)list[index - 1]; for (var i = 0; i < list.Count; i++) { var other = (JObject)list[i]; if (ReferenceEquals(other, target) || !((bool?)other["customTitle"] ?? false)) continue; if (string.Equals((string)other["title"], title, StringComparison.OrdinalIgnoreCase)) { CPH.SendMessage("That title already exists."); return false; } } target["title"] = title; target["customTitle"] = true; Save(data); CPH.SetArgument("replayNumber", index); CPH.SetArgument("replayTitle", title); SendStoreMessage("name"); return true; }
    public bool ListPlaylist() { var list = GetCatalog(Load()); var message = list.Count == 0 ? "The replay playlist is empty." : string.Join(" | ", list.OfType<JObject>().Select((x, i) => "#" + (i + 1) + " " + (string)x["title"])); CPH.SetArgument("replayPlaylist", message); SendStoreMessage("playlist"); return true; }
    private void SendStoreMessage(string type) { var key = "rts.actionreplay.message." + type; var text = CPH.GetGlobalVar<string>(key + ".text", true); if (string.IsNullOrWhiteSpace(text)) return; text = CPH.Parse(text); if (CPH.GetGlobalVar<bool?>(key + ".chat", true) ?? true) CPH.SendMessage(text); if (CPH.GetGlobalVar<bool?>(key + ".overlay", true) ?? false) { CPH.SetArgument("replayCommand", "message"); CPH.SetArgument("replayMessage", text); SetMessageStyleArguments(); CPH.TriggerEvent("RTS-Action Replay", true); } }
    private void SetMessageStyleArguments() { CPH.SetArgument("replayLogoUrl", CPH.GetGlobalVar<string>("rts.actionreplay.brandLogoUrl", true) ?? ""); CPH.SetArgument("replayMessageBoardColor", CPH.GetGlobalVar<string>("rts.actionreplay.clapper.boardColor", true) ?? "#101416"); CPH.SetArgument("replayMessageStripeLight", CPH.GetGlobalVar<string>("rts.actionreplay.clapper.stripeLight", true) ?? "#EEEEEE"); CPH.SetArgument("replayMessageStripeDark", CPH.GetGlobalVar<string>("rts.actionreplay.clapper.stripeDark", true) ?? "#111111"); CPH.SetArgument("replayMessageAccent", CPH.GetGlobalVar<string>("rts.actionreplay.clapper.accent", true) ?? "#0384CB"); CPH.SetArgument("replayMessageTextColor", CPH.GetGlobalVar<string>("rts.actionreplay.clapper.textColor", true) ?? "#0384CB"); CPH.SetArgument("replayMessageFont", CPH.GetGlobalVar<string>("rts.actionreplay.clapper.font", true) ?? "Arial, sans-serif"); CPH.SetArgument("replayClapperPosition", CPH.GetGlobalVar<string>("rts.actionreplay.clapper.position", true) ?? "Centered"); CPH.SetArgument("replayClapperPositions", CPH.GetGlobalVar<string>(ClapperPositionsKey, true) ?? "{\"Centered\":{\"name\":\"Centered\",\"tag\":\"centered\",\"scale\":50,\"scaleX\":50,\"scaleY\":50,\"x\":0,\"y\":0,\"z\":0,\"rotateX\":0,\"rotateY\":0,\"rotateZ\":0,\"fov\":90}}"); CPH.ExecuteMethod("RTS - Action Replay - Core - Resolver", "ResolveClapperAnimation"); CPH.SetArgument("replayClapperWidth", ClapperboardPreviewWidth); CPH.SetArgument("replayClapperHeight", ClapperboardPreviewHeight); CPH.SetArgument("replayMessageDuration", GetSettingInt("rts.actionreplay.clapper.duration", 5000)); }

    private int GetSettingInt(string key, int fallback) { try { object value = CPH.GetGlobalVar<object>(key, true); return value == null ? fallback : Convert.ToInt32(value, System.Globalization.CultureInfo.InvariantCulture); } catch { return fallback; } }
    private bool IsReplayFile(string path) { var extension = Path.GetExtension(path); if (string.IsNullOrWhiteSpace(extension)) return false; var configured = CPH.GetGlobalVar<string>(FileTypesKey, true) ?? ".mp4, .mkv"; foreach (var raw in configured.Split(new[] { ',', ';' }, StringSplitOptions.RemoveEmptyEntries)) { var type = raw.Trim(); if (!type.StartsWith(".")) type = "." + type; if (extension.Equals(type, StringComparison.OrdinalIgnoreCase)) return true; } return false; }
    private bool Stable(string path) { try { var a = new FileInfo(path).Length; System.Threading.Thread.Sleep(250); return new FileInfo(path).Length == a; } catch { return false; } }
    private string Get(string name) { CPH.TryGetArg(name, out string value); return value ?? ""; }
    private string NormalizePlatform(string userType) { if (string.Equals(userType, "YouTube", StringComparison.OrdinalIgnoreCase)) return "YouTube"; if (string.Equals(userType, "Kick", StringComparison.OrdinalIgnoreCase)) return "Kick"; return "Twitch"; }
    private void ApplyPendingCreator(ref string platform, ref string id, ref string name) { var raw = CPH.GetGlobalVar<string>(PendingKey, false); if (string.IsNullOrWhiteSpace(raw)) return; try { var pending = JObject.Parse(raw); if (!string.IsNullOrWhiteSpace((string)pending["platform"])) platform = NormalizePlatform((string)pending["platform"]); if (!string.IsNullOrWhiteSpace((string)pending["id"])) id = (string)pending["id"]; if (!string.IsNullOrWhiteSpace((string)pending["name"])) name = (string)pending["name"]; } catch { } }
    private JObject Load() { var raw = CPH.GetGlobalVar<string>(DataKey, true); try { return string.IsNullOrWhiteSpace(raw) ? new JObject() : JObject.Parse(raw); } catch { return new JObject(); } }
    private void Save(JObject data) => CPH.SetGlobalVar(DataKey, data.ToString(Newtonsoft.Json.Formatting.None), true);
    private void Save(string key, JObject value) => CPH.SetGlobalVar(key, value.ToString(Newtonsoft.Json.Formatting.None), true);

    private JArray GetCatalog(JObject data) { var catalog = data["catalog"] as JArray; if (catalog != null) return catalog; var legacy = CPH.GetGlobalVar<string>(LegacyCatalogKey, true); try { catalog = string.IsNullOrWhiteSpace(legacy) ? new JArray() : JArray.Parse(legacy); } catch { catalog = new JArray(); } data["catalog"] = catalog; return catalog; }


    // Consolidated preset/config persistence from RTSActionReplayPresetStore.
    private JObject Read(string key, JObject fallback) { var raw = CPH.GetGlobalVar<string>(key, true); try { return string.IsNullOrWhiteSpace(raw) ? fallback : JObject.Parse(raw); } catch { return fallback; } }

    const string ClapperKey = "rts.actionreplay.config.clapper";

    const string PresetsKey = "rts.actionreplay.config.presets";

    public bool EnsureDefaults() { var p = Read(PresetsKey, Defaults()); var d = Defaults(); if (!(p["branding"] is JArray)) p["branding"] = d["branding"]; if (!(p["visual"] is JArray)) p["visual"] = d["visual"]; if (!(p["title"] is JArray)) p["title"] = TitleDefaults(); MigrateBranding(p); EnsureBranding(p); EnsureVisuals(p); EnsureTitlePresets(p); p["version"] = 4; Save(PresetsKey, p); CPH.ExecuteMethod("RTS - Action Replay - Core - Resolver", "EnsurePositions"); return true; }

    public bool EnsureEntryPoints() { EnsureDefaults(); var player = Read(PlayerKey, new JObject()); var panel = Read(PanelKey, new JObject()); var clapper = Read(ClapperKey, new JObject()); MigratePlayer(player); MigratePanel(panel); MigrateClapper(clapper); Save(PlayerKey, player); Save(PanelKey, panel); Save(ClapperKey, clapper); return true; }

    public JArray Branding() => Read(PresetsKey, Defaults())["branding"] as JArray ?? new JArray();

    public JArray Visuals() => Read(PresetsKey, Defaults())["visual"] as JArray ?? new JArray();

    public JArray Titles() => Read(PresetsKey, Defaults())["title"] as JArray ?? new JArray();

    static JObject Find(JArray a, string id) { foreach (var x in a ?? new JArray()) if (string.Equals((string)x["id"], id, StringComparison.OrdinalIgnoreCase)) return x as JObject; return null; }

    static string ResolveId(JArray a, string id) { var x = Find(a, id); return x == null ? null : (string)x["id"]; }

    static string Normalize(string v) { v = (v ?? "").Trim().ToLowerInvariant(); return v == "cinematic" || v == "cut" || v == "minimal" ? v : "broadcast"; }

    static void Put(JObject c, string id, JObject e) { var a = c["entryPoints"] as JObject ?? new JObject(); a[id] = e; c["entryPoints"] = a; }

    void MigratePlayer(JObject p) { var a = (p["animation"] as JObject)?["entryPoints"] as JObject; var old = (string)(p["title"] as JObject)?["selectedProfile"] ?? G("rts.actionreplay.titleBarStyle", "Broadcast"); var visual = Normalize(old); var entries = p["entryPoints"] as JObject ?? new JObject(); var legacyPlay = entries["catalog"] as JObject ?? entries["recent"] as JObject ?? new JObject(); foreach (var id in new[] { "obs", "twitch", "youtube", "kick", "play" }) { var source = id == "play" ? legacyPlay : entries[id] as JObject; var e = source == null ? new JObject() : (JObject)source.DeepClone(); e["animationProfile"] = (string)e["animationProfile"] ?? (string)a?[id] ?? "default"; e["visualPreset"] = (string)e["visualPreset"] ?? visual; e["titlePreset"] = (string)e["titlePreset"] ?? "default"; e["brandingPreset"] = MigrateBrandingId((string)e["brandingPreset"] ?? LegacyBranding(visual)); if (id == "play") e["useSourcePlatformBranding"] = (bool?)e["useSourcePlatformBranding"] ?? false; Put(p, id, e); } foreach (var id in new[] { "recent", "catalog", "playlist" }) entries.Remove(id); p["entryPoints"] = entries; }

    void MigratePanel(JObject p) { var old = (p["preset"] as JObject) ?? new JObject(); var fallback = (string)old["fallback"] ?? "Broadcast"; var legacy = (old["entryPoints"] as JObject) ?? new JObject(); var anim = (p["animation"] as JObject)?["entryPoints"] as JObject; foreach (var id in new[] { "recent", "playlist", "creatorLeaderboard" }) { var e = p["entryPoints"]?[id] as JObject ?? new JObject(); e["animationProfile"] = (string)e["animationProfile"] ?? (string)anim?[id] ?? "default"; var visual = Normalize((string)legacy[id] ?? fallback); e["visualPreset"] = (string)e["visualPreset"] ?? visual; e["titlePreset"] = (string)e["titlePreset"] ?? "default"; e["brandingPreset"] = MigrateBrandingId((string)e["brandingPreset"] ?? LegacyBranding(visual)); Put(p, id, e); } }

    void MigrateClapper(JObject c) { var e = c["entryPoint"] as JObject ?? new JObject(); e["animationProfile"] = (string)e["animationProfile"] ?? (string)(c["animation"] as JObject)?["selectedProfile"] ?? "default"; e.Remove("visualPreset"); e.Remove("titlePreset"); e["brandingPreset"] = MigrateBrandingId((string)e["brandingPreset"] ?? "default"); c["entryPoint"] = e; }

    JObject Resolve(JObject c, string ep, string[] valid) { var a = c["entryPoints"] as JObject ?? new JObject(); var id = string.IsNullOrWhiteSpace(ep) ? valid[0] : ep.Trim().ToLowerInvariant(); if (Array.IndexOf(valid, id) < 0) id = valid[0]; var e = a[id] as JObject ?? new JObject(); return new JObject { { "animationProfile", (string)e["animationProfile"] ?? "default" }, { "designPreset", ResolveId(Visuals(), (string)e["designPreset"] ?? (string)e["visualPreset"] ?? "broadcast") ?? "broadcast" }, { "titlePreset", ResolveId(Titles(), (string)e["titlePreset"] ?? "default") ?? "default" }, { "brandingPreset", ResolveId(Branding(), (string)e["brandingPreset"] ?? "default") ?? "default" }, { "useSourcePlatformBranding", (bool?)e["useSourcePlatformBranding"] ?? false } }; }

    JObject ResolveClapper() { var c = Read(ClapperKey, new JObject()); var e = c["entryPoint"] as JObject ?? new JObject(); return new JObject { { "animationProfile", (string)e["animationProfile"] ?? "default" }, { "brandingPreset", ResolveId(Branding(), (string)e["brandingPreset"] ?? "default") ?? "default" } }; }

    string LegacyBranding(string v) => v == "cut" ? "twitch" : v == "broadcast" ? "rts" : "default";

    string MigrateBrandingId(string id) { if (string.Equals(id, "legacy-broadcast", StringComparison.OrdinalIgnoreCase)) return "rts"; if (string.Equals(id, "legacy-cut", StringComparison.OrdinalIgnoreCase)) return "twitch"; return id; }

    string G(string k, string d) => CPH.GetGlobalVar<string>(k, true) ?? d;

    JObject Defaults() { return new JObject { { "version", 4 }, { "branding", new JArray( new JObject { { "id", "default" }, { "name", "Default" }, { "platform", "" }, { "primaryColor", "#0384CBFF" }, { "secondaryColor", "#101416FF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#0384CBFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "" }, { "fallbackText", "RTS" }, { "brandLabel", "ACTION REPLAY" } }, new JObject { { "id", "rts" }, { "name", "RTS" }, { "platform", "" }, { "primaryColor", "#0384CBFF" }, { "secondaryColor", "#FFD400FF" }, { "titleColor", "#FFD400FF" }, { "titlePrefixSuffixColor", "#0384CBFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "" }, { "fallbackText", "RTS" }, { "brandLabel", "ACTION REPLAY" } }, new JObject { { "id", "twitch" }, { "name", "Twitch" }, { "platform", "Twitch" }, { "primaryColor", "#9146FFFF" }, { "secondaryColor", "#FFFFFFFF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#FFFFFFFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "https://www.freepnglogos.com/uploads/twitch-logo-vector-png-2.png" }, { "fallbackText", "Twitch" }, { "brandLabel", "" } }, new JObject { { "id", "youtube" }, { "name", "YouTube" }, { "platform", "YouTube" }, { "primaryColor", "#D4101DFF" }, { "secondaryColor", "#FFFFFFFF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#FFFFFFFF" }, { "textColor", "#FFFFFFFF" }, { "shadowColor", "#FFFFFFFF" }, { "font", "Oswald" }, { "fontSize", 34 }, { "logo", "https://www.freepnglogos.com/uploads/youtube-logo-png/youtube-transparent-youtube-icon-29.png" }, { "fallbackText", "YouTube" }, { "brandLabel", "" } }, new JObject { { "id", "kick" }, { "name", "Kick" }, { "platform", "Kick" }, { "primaryColor", "#53FC18FF" }, { "secondaryColor", "#FFFFFFFF" }, { "titleColor", "#FFFFFFFF" }, { "titlePrefixSuffixColor", "#FFFFFFFF" }, { "textColor", "#000000FF" }, { "shadowColor", "#000000FF" }, { "font", "Inter" }, { "fontSize", 34 }, { "logo", "https://static.kick.com/kick-logo.svg" }, { "fallbackText", "Kick" }, { "brandLabel", "" } } )}, { "visual", new JArray( new JObject { { "id", "broadcast" }, { "name", "Broadcast" }, { "chevronHeight", 42 }, { "randomHeight", false }, { "chevronWidth", 42 }, { "randomWidth", false }, { "chevronSpacing", 0 }, { "randomSpacing", false }, { "chevronSpeed", 95 }, { "showTitle", true }, { "design", "broadcast" }, }, new JObject { { "id", "cinematic" }, { "name", "Cinematic" }, { "fixed", true }, { "design", "cinematic" }, }, new JObject { { "id", "cut" }, { "name", "Cut" }, { "blockWidth", 170 }, { "randomWidth", true }, { "barHeight", 5 }, { "showTitle", true }, { "design", "cut" }, }, new JObject { { "id", "minimal" }, { "name", "Minimal" }, { "fixed", true }, { "design", "minimal" }, } )} }; }

    JArray TitleDefaults() { var d = new JObject { { "id", "default" }, { "name", "Default" }, { "decorationPosition", G("rts.actionreplay.titleDecorationPosition", "Prefix") }, { "decoration", G("rts.actionreplay.titleDecoration", "Action Replay -") }, { "position", G("rts.actionreplay.titlePosition", "Bottom") }, { "animation", G("rts.actionreplay.titleAnimation", "Left to right") }, { "delay", CPH.GetGlobalVar<int?>("rts.actionreplay.titleDelay", true) ?? 2000 }, { "duration", CPH.GetGlobalVar<int?>("rts.actionreplay.titleDuration", true) ?? 10000 }, { "animationDuration", CPH.GetGlobalVar<int?>("rts.actionreplay.titleAnimationDuration", true) ?? 1000 } }; return new JArray(d); }

    void MigrateBranding(JObject p) { var a = p["branding"] as JArray ?? new JArray(); for (var i = a.Count - 1; i >= 0; i--) { var x = a[i] as JObject; var id = (string)x?["id"]; if (string.Equals(id, "legacy-broadcast", StringComparison.OrdinalIgnoreCase) || string.Equals(id, "legacy-cut", StringComparison.OrdinalIgnoreCase)) { a.RemoveAt(i); continue; } var platform = (string)x?["platform"]; if (string.Equals(platform, "Twitch", StringComparison.OrdinalIgnoreCase)) x["id"] = "twitch"; else if (string.Equals(platform, "YouTube", StringComparison.OrdinalIgnoreCase)) x["id"] = "youtube"; else if (string.Equals(platform, "Kick", StringComparison.OrdinalIgnoreCase)) x["id"] = "kick"; } foreach (var def in Defaults()["branding"] as JArray) { var id = (string)def["id"]; if (Find(a, id) == null) a.Add(def.DeepClone()); } p["branding"] = a; }

    void EnsureBranding(JObject p) { var a = p["branding"] as JArray ?? new JArray(); foreach (var x in a) if (x["platform"] == null) x["platform"] = ""; p["branding"] = a; }

    void EnsureVisuals(JObject p) { var a = p["visual"] as JArray ?? new JArray(); var d = Defaults()["visual"] as JArray; foreach (var id in new[] { "broadcast", "cinematic", "cut", "minimal" }) { var x = Find(a, id); var def = Find(d, id); if (x == null) { a.Add(def.DeepClone()); continue; } if (x["design"] == null) x["design"] = (string)def["design"]; if (x["name"] == null) x["name"] = (string)def["name"]; foreach (var f in new[] { "chevronHeight", "randomHeight", "chevronWidth", "randomWidth", "chevronSpacing", "randomSpacing", "chevronSpeed", "blockWidth", "barHeight" }) if (x[f] == null && def[f] != null) x[f] = def[f]; } p["visual"] = a; }

    void EnsureTitlePresets(JObject p) { var a = p["title"] as JArray ?? new JArray(); if (a.Count == 0) a = TitleDefaults(); foreach (var x in a) { if (x["name"] == null) x["name"] = (string)x["id"] ?? "Title Preset"; if (x["decorationPosition"] == null) x["decorationPosition"] = "Prefix"; if (x["position"] == null) x["position"] = "Bottom"; if (x["animation"] == null) x["animation"] = "Left to right"; if (x["delay"] == null) x["delay"] = 2000; if (x["duration"] == null) x["duration"] = 10000; if (x["animationDuration"] == null) x["animationDuration"] = 1000; } p["title"] = a; }
}
